import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

type Language = "en" | "nl";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.howItWorks": "How It Works",
    "nav.features": "Features",
    "nav.security": "Security",
    "nav.pricing": "Pricing",
    "nav.impact": "Impact",
    "nav.about": "About",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "nav.blog": "Blog",
    "nav.home": "Home",
    "nav.signIn": "Sign In",
    "nav.getStarted": "Get Started",

    // Hero
    "hero.badge": "Financial Clarity for Everyone",
    "hero.title1": "Bring Structure &",
    "hero.titleHighlight": "Clarity",
    "hero.title2": "to Your Finances",
    "hero.desc": "FAB is an intelligent financial orchestration platform that automates your bookkeeping, connects your existing tools, and gives you a complete picture of your finances — all in less than 10 minutes per week.",
    "hero.cta1": "Get Started Free",
    "hero.cta2": "See How It Works",
    "hero.stat1": "<10 min/week",
    "hero.stat2": "E2E Encrypted",
    "hero.stat3": "Desktop & Mobile",

    // Problem
    "problem.label": "The Challenge",
    "problem.title": "Managing Finances Shouldn't Be a Full-Time Job",
    "problem.desc": "For individuals managing disability or chronic illness, financial administration is scattered across WhatsApp messages, email inboxes, Google Drive folders, and multiple platforms. This chaos consumes hours every week — time better spent on health and well-being.",
    "problem.card1.title": "Scattered Documents",
    "problem.card1.desc": "Receipts in WhatsApp, invoices in Gmail, statements in Drive. No single source of truth for your finances.",
    "problem.card1.stat": "5+",
    "problem.card1.statLabel": "data sources",
    "problem.card2.title": "Hours of Manual Work",
    "problem.card2.desc": "Manually entering transactions, chasing vendors for missing information, reconciling across platforms.",
    "problem.card2.stat": "4-8",
    "problem.card2.statLabel": "hours per week",
    "problem.card3.title": "Hidden Health Costs",
    "problem.card3.desc": "The true financial impact of disability remains invisible — spread across earmarked funds, insurance, and out-of-pocket expenses.",
    "problem.card3.stat": "€17K+",
    "problem.card3.statLabel": "extra annual costs",

    // How It Works
    "hiw.label": "How It Works",
    "hiw.title": "From Chaos to Clarity in Four Steps",
    "hiw.desc": "FAB works quietly in the background, transforming scattered financial data into structured, actionable clarity.",
    "hiw.step1.title": "Connect & Manage Your Platforms",
    "hiw.step1.desc": "Authorize FAB to access and manage your accounts on MijnGeldzaken.nl, WaveApps, SVB, banks, Gmail, and more.",
    "hiw.step2.title": "AI Extracts & Categorizes",
    "hiw.step2.desc": "Our AI scans your sources, extracts financial data using OCR, and intelligently categorizes every transaction.",
    "hiw.step3.title": "Auto-Route & Manage",
    "hiw.step3.desc": "FAB logs into each platform to create entries, update records, and keep everything synchronized. Missing data? FAB emails vendors on your behalf.",
    "hiw.step4.title": "Review & Relax",
    "hiw.step4.desc": "Spend less than 10 minutes per week reviewing only what the AI is uncertain about. Everything else is handled.",

    // Features
    "features.orch.label": "Intelligent Orchestration",
    "features.orch.title": "One Platform, All Your Financial Tools",
    "features.orch.desc": "FAB connects to mijngeldzaken.nl, WaveApps, SVB, and your bank accounts — pulling, pushing, and updating transactions across all platforms in real-time.",
    "features.orch.item1": "Bidirectional sync with all platforms",
    "features.orch.item2": "Earmarked fund mapping for PGB",
    "features.orch.item3": "Hourly synchronization cycles",
    "features.orch.item4": "Conflict detection and resolution",
    "features.ai.label": "AI-Powered Processing",
    "features.ai.title": "Self-Completing, Self-Healing Books",
    "features.ai.desc": "FAB's AI doesn't just categorize — it identifies missing data, crafts professional emails to vendors, and automatically updates your books when responses arrive.",
    "features.ai.item1": "OCR scanning of receipts and invoices",
    "features.ai.item2": "Autonomous vendor communication",
    "features.ai.item3": "Confidence-based flagging system",
    "features.ai.item4": "Continuous learning from corrections",
    "features.dash.label": "Unified Dashboard",
    "features.dash.title": "See Your Complete Financial Picture",
    "features.dash.desc": "For the first time, see all your finances in one place — household expenses, side-hustle income, healthcare costs, and earmarked funds. FAB quantifies your true \"disability cost premium\" and identifies tax-deductible expenses automatically.",
    "features.dash.item1": "Real-time cost tracking dashboard",
    "features.dash.item2": "Healthcare cost quantification reports",
    "features.dash.item3": "Annual tax summary generation",
    "features.dash.item4": "Export in universal formats (CSV, PDF)",

    // Integrations
    "integrations.label": "Connected Platforms",
    "integrations.title": "FAB Manages Your Existing Tools",
    "integrations.desc": "FAB isn't another standalone finance app. It's an orchestration layer that connects to the platforms you already use — logging in, creating entries, updating records, and keeping everything synchronized across your entire financial ecosystem.",
    "integrations.mgz.title": "MijnGeldzaken.nl",
    "integrations.mgz.desc": "FAB logs into your MijnGeldzaken account, creates household bookings, categorizes transactions, and maintains your complete household financial administration — automatically.",
    "integrations.mgz.tag": "Household Finance",
    "integrations.wave.title": "Wave Apps",
    "integrations.wave.desc": "FAB manages your Wave accounting — creating invoices, recording expenses, reconciling bank transactions, and maintaining separate books for business and healthcare costs.",
    "integrations.wave.tag": "Accounting",
    "integrations.banks.title": "Dutch Banks",
    "integrations.banks.desc": "Direct PSD2 open banking connections to ING, ABN AMRO, Rabobank, and more. FAB pulls transaction feeds in real-time and matches them to your bookkeeping entries.",
    "integrations.banks.tag": "Banking",
    "integrations.svb.title": "SVB (Sociale Verzekeringsbank)",
    "integrations.svb.desc": "FAB handles your PGB declarations, tracks budget utilization, submits care worker payment requests, and monitors approval statuses — all within your SVB account.",
    "integrations.svb.tag": "PGB Management",
    "integrations.google.title": "Gmail & Google Drive",
    "integrations.google.desc": "FAB scans your inbox for invoices and receipts, monitors Drive folders for financial documents, and automatically processes everything it finds.",
    "integrations.google.tag": "Document Sources",
    "integrations.more.title": "More Integrations Coming",
    "integrations.more.desc": "We're continuously expanding our platform connections. WhatsApp Business, Exact Online, Moneybird, and more are on our roadmap.",
    "integrations.more.tag": "Roadmap",
    "integrations.callout.title": "Not just connecting — actively managing",
    "integrations.callout.desc": "Unlike traditional aggregators that only read your data, FAB performs bidirectional operations. It logs into MijnGeldzaken.nl to create bookings, manages your Wave invoices, and submits PGB declarations to SVB — all orchestrated from one intelligent platform.",
    "integrations.cta": "See How It Works",

    // Stats
    "stats.users": "Potential Users in NL",
    "stats.usersSub": "PGB, Wajong & WIA recipients",
    "stats.budget": "PGB Budget Managed",
    "stats.budgetSub": "Annually by SVB",
    "stats.minutes": "Minutes Per Week",
    "stats.minutesSub": "User time required",
    "stats.saved": "Time Saved",
    "stats.savedSub": "On financial admin",

    // Testimonials
    "testimonials.label": "What People Say",
    "testimonials.title": "Trusted by Early Adopters",
    "testimonials.desc": "Hear from the people who have experienced FAB firsthand during our early access program.",
    "testimonials.t1.quote": "FAB completely changed how I manage my PGB. What used to take me 6 hours a week now happens automatically. I finally have time for what matters — my health.",
    "testimonials.t1.name": "Sarah M.",
    "testimonials.t1.role": "PGB Holder, Amsterdam",
    "testimonials.t2.quote": "As a caregiver for my mother, I was drowning in paperwork. FAB brought everything together in one place. The AI categorization is remarkably accurate.",
    "testimonials.t2.name": "Thomas K.",
    "testimonials.t2.role": "Family Caregiver, Utrecht",
    "testimonials.t3.quote": "I was skeptical about another finance app, but FAB is different. It actually understands the Dutch healthcare system. The WMO integration alone saved me hours.",
    "testimonials.t3.name": "Lisa van D.",
    "testimonials.t3.role": "WIA Recipient, Rotterdam",
    "testimonials.t4.quote": "The privacy-first approach sold me. My financial data stays on my device, and the end-to-end encryption gives me real peace of mind. This is how fintech should work.",
    "testimonials.t4.name": "Mark B.",
    "testimonials.t4.role": "Financial Advisor, Den Haag",
    "testimonials.trustBadge1": "Privacy First",
    "testimonials.trustBadge2": "GDPR Compliant",
    "testimonials.trustBadge3": "Dutch-Built",
    "testimonials.trustBadge4": "Open Source Core",

    // Blog / Updates
    "blog.label": "Latest Updates",
    "blog.title": "News & Insights",
    "blog.desc": "Stay up to date with FAB's development journey, product milestones, and insights on financial accessibility.",
    "blog.readMore": "Read More",
    "blog.viewAll": "View All Updates",
    "blog.backToBlog": "Back to Blog",
    "blog.publishedOn": "Published on",
    "blog.minRead": "min read",
    "blog.noPosts": "No posts yet. Check back soon!",
    "blog.pageTitle": "Blog & Updates",
    "blog.pageDesc": "Product milestones, feature previews, and insights on making financial management accessible for everyone.",
    "blog.badge": "Blog & Updates",
    "blog.searchPlaceholder": "Search articles...",
    "blog.allPosts": "All Posts",
    "blog.catUpdate": "Update",
    "blog.catMilestone": "Milestone",
    "blog.catFeature": "Feature",
    "blog.catAnnouncement": "Announcement",
    "blog.catTechnology": "Technology",
    "blog.catGuide": "Guide",
    "blog.noPostsDesc": "We're working on new content. Check back soon for updates on FAB's development.",
    "blog.readTime": "read",
    "blog.postNotFound": "Post Not Found",
    "blog.postNotFoundDesc": "The blog post you're looking for doesn't exist or has been removed.",
    "blog.ctaTitle": "Enjoyed this article?",
    "blog.ctaDesc": "Explore more updates and insights about FAB's journey.",
    "blog.ctaButton": "Browse All Posts",

    // Security
    "security.label": "Privacy & Security",
    "security.title": "Your Data Stays Yours",
    "security.desc": "FAB is built with privacy at its core. Your financial data is stored locally on your device, protected by end-to-end encryption, and fully compliant with Dutch and EU regulations.",
    "security.e2e": "E2E Encryption",
    "security.e2eDesc": "All data encrypted in transit and at rest",
    "security.gdpr": "GDPR Compliant",
    "security.gdprDesc": "Full compliance with Dutch AP regulations",
    "security.bio": "Biometric Login",
    "security.bioDesc": "Fingerprint and face recognition support",
    "security.export": "Data Export",
    "security.exportDesc": "Export or delete all your data anytime",
    "security.local": "Locally installed — data never leaves your device",
    "security.2fa": "Two-factor authentication (2FA)",
    "security.emailApproval": "Email approvals before autonomous sends",
    "security.offline": "Works fully offline — syncs when connected",
    "security.gdprExport": "GDPR data export and permanent deletion",
    "security.trusted": "Trusted person read-only access option",

    // Pricing
    "pricing.label": "Pricing",
    "pricing.title": "Pay Only for What You Use",
    "pricing.desc": "FAB uses a transparent, resource-based pricing model. You only pay for the resources you consume — no hidden fees, no surprises.",
    "pricing.free.label": "Free Tier",
    "pricing.free.price": "€0",
    "pricing.free.period": "/forever",
    "pricing.free.desc": "Get started and experience FAB's core value.",
    "pricing.free.item1": "3 transactions per week",
    "pricing.free.item2": "All platform integrations",
    "pricing.free.item3": "AI categorization",
    "pricing.free.item4": "Basic reporting",
    "pricing.free.item5": "Desktop & mobile access",
    "pricing.free.cta": "Start Free",
    "pricing.payg.label": "Pay As You Go",
    "pricing.payg.formula": "Usage × 2.5",
    "pricing.payg.desc": "Fair, transparent pricing based on actual resource usage.",
    "pricing.payg.item1": "Unlimited transactions",
    "pricing.payg.item2": "Autonomous data completion",
    "pricing.payg.item3": "Full email automation",
    "pricing.payg.item4": "Advanced reporting & tax summaries",
    "pricing.payg.item5": "Real-time cost dashboard",
    "pricing.payg.item6": "Configurable spending cap",
    "pricing.payg.item7": "Priority support",
    "pricing.payg.cta": "Get Started",

    // Impact
    "impact.label": "Social Impact",
    "impact.title": "Measuring the True Cost of Disability",
    "impact.desc": "FAB is more than a financial tool. By aggregating anonymized data, we can publish first-of-its-kind reports on the true financial burden of living with a disability — providing evidence for better policy and support.",
    "impact.card1.title": "Financial Empowerment",
    "impact.card1.desc": "Give back time and energy to individuals who need it most.",
    "impact.card2.title": "Cost Transparency",
    "impact.card2.desc": "Quantify the true 'disability cost premium' at population scale.",
    "impact.card3.title": "Policy Evidence",
    "impact.card3.desc": "Anonymized data to inform better disability policy and support.",
    "impact.card4.title": "Community Strength",
    "impact.card4.desc": "Build a network of empowered individuals who understand their financial reality.",

    // CTA
    "cta.title": "Ready to Bring Clarity to Your Finances?",
    "cta.desc": "Join the movement towards financial empowerment. Start with 3 free transactions per week and experience the difference.",
    "cta.primary": "Get Started Free",
    "cta.secondary": "Contact Us",

    // Footer
    "footer.desc": "Financial Structure & Clarity for individuals managing complex health-related finances in the Netherlands.",
    "footer.product": "Product",
    "footer.company": "Company",
    "footer.legal": "Legal",
    "footer.rights": "All rights reserved.",
    "footer.madeWith": "Made with",
    "footer.inNL": "in the Netherlands",

    // Contact page
    "contact.badge": "Get in Touch",
    "contact.title1": "Let's Start a",
    "contact.titleHighlight": "Conversation",
    "contact.desc": "Have questions about FAB? Want to learn how we can bring clarity to your finances? We'd love to hear from you.",
    "contact.form.firstName": "First Name",
    "contact.form.lastName": "Last Name",
    "contact.form.email": "Email Address",
    "contact.form.topic": "Topic",
    "contact.form.topicPlaceholder": "Select a topic",
    "contact.form.message": "Message",
    "contact.form.messagePlaceholder": "Tell us how we can help you...",
    "contact.form.send": "Send Message",
    "contact.form.sending": "Sending...",
    "contact.success.title": "Message Sent!",
    "contact.success.desc": "Thank you for reaching out. We'll get back to you within 24 hours.",
    "contact.success.another": "Send Another Message",
    "contact.success.backHome": "Back to Home",
    "contact.success.toast": "Message sent successfully!",
    "contact.info.email": "Email Us",
    "contact.info.response": "Response Time",
    "contact.info.responseVal": "Within 24 hours",
    "contact.info.location": "Location",
    "contact.info.locationVal": "The Netherlands",
    "contact.info.phone": "Phone",
    "contact.info.phoneVal": "Schedule a call",
    "contact.info.faq": "Check our FAQ",
    "contact.info.faqDesc": "Check our frequently asked questions for instant answers to common inquiries about FAB's features, pricing, and security.",
    "contact.info.faqLink": "Visit FAQ",
    "contact.topic.select": "Select a topic...",
    "contact.topic.general": "General Inquiry",
    "contact.topic.demo": "Request a Demo",
    "contact.topic.pricing": "Pricing & Plans",
    "contact.topic.partnership": "Partnership Opportunities",
    "contact.topic.support": "Technical Support",
    "contact.topic.accessibility": "Accessibility Question",
    "contact.topic.media": "Media & Press",
    "contact.error.firstName": "First name is required",
    "contact.error.lastName": "Last name is required",
    "contact.error.email": "Email is required",
    "contact.error.emailInvalid": "Please enter a valid email address",
    "contact.error.subject": "Please select a topic",
    "contact.error.message": "Message is required",
    "contact.error.messageLength": "Message must be at least 10 characters",
    "contact.toast.schedule": "Scheduling feature coming soon",
    "contact.form.firstNamePlaceholder": "Your first name",
    "contact.form.lastNamePlaceholder": "Your last name",
    "contact.form.emailPlaceholder": "you@example.com",
    "contact.form.messagePlaceholderLong": "Tell us how we can help...",

    // FAQut page
    "about.badge": "Our Story",
    "about.title1": "Born from",
    "about.titleHighlight": "Lived Experience",
    "about.title2": "Built for Real People",
    "about.mission.label": "Our Mission",
    "about.mission.title": "Financial Clarity in Less Than 10 Minutes a Week",
    "about.different.label": "What Makes Us Different",
    "about.values.label": "Our Values",
    "about.impact.label": "Our Impact Vision",
    "about.cta.title": "Join Us in Building Financial Clarity",
    "about.cta.desc": "Whether you're a PGB holder, a Wajong recipient, or managing finances with a chronic condition — FAB is built for you.",
    "about.cta.primary": "Get Started Free",
    "about.cta.secondary": "Contact Us",
    "about.hero.desc": "FAB was not created in a boardroom. It was born from the daily reality of managing a household while navigating the financial complexity that comes with chronic illness and disability. We understand the struggle because we have lived it.",
    "about.problem.title1": "The Problem",
    "about.problem.titleHighlight": "We Lived",
    "about.problem.p1": "Living with a chronic illness or disability in the Netherlands means navigating a labyrinth of financial obligations. Your household expenses are tracked in one place, your PGB (Persoonsgebonden Budget) payments flow through SVB, your side-hustle income lives in WaveApps, and critical receipts are scattered across WhatsApp messages, Gmail inboxes, and Google Drive folders.",
    "about.problem.p2": "The result is financial chaos. Hours spent every week manually entering data, chasing missing receipts, and trying to reconcile accounts across platforms that were never designed to talk to each other. Hours that people managing health conditions simply do not have.",
    "about.problem.p3pre": "Worse still, this fragmentation makes it impossible to answer a fundamental question:",
    "about.problem.p3quote": "What does my illness or disability actually cost me?",
    "about.problem.p3post": "Without that answer, there is no clarity, no control, and no path to financial stability.",
    "about.mission.subtitle": "Financial Structure and Clarity,",
    "about.mission.subtitleHighlight": "Without the Burden",
    "about.mission.desc": "Our mission is to give individuals managing health-related financial complexity the one thing they deserve but rarely have: complete financial clarity with minimal effort. We believe that managing your finances should take less than 10 minutes per week, not 10 hours.",
    "about.mission.pillar1.title": "Automate the Chaos",
    "about.mission.pillar1.desc": "FAB automatically extracts financial data from WhatsApp, Gmail, Google Drive, and photos. It categorizes, fills in the blanks, and routes every transaction to the correct platform — so you do not have to.",
    "about.mission.pillar2.title": "Orchestrate Your Ecosystem",
    "about.mission.pillar2.desc": "We do not replace your existing tools. FAB connects mijngeldzaken.nl, WaveApps, SVB, and your bank accounts into one unified, synchronized system. Every euro is tracked on its complete journey.",
    "about.mission.pillar3.title": "Reveal the True Cost",
    "about.mission.pillar3.desc": "For the first time, you can see exactly what your health condition costs you. FAB quantifies the hidden financial burden of disability — the costs that healthy individuals never face.",
    "about.different.subtitle": "Not Just Another",
    "about.different.subtitleHighlight": "Finance App",
    "about.different.desc": "Most financial tools ask you to do the work. FAB does the work for you. Here is what sets us apart.",
    "about.different.item1.title": "Self-Completing Books",
    "about.different.item1.desc": "When FAB finds missing information in your records — a vendor name, an invoice number, an amount — it does not just flag it. It autonomously crafts and sends an email on your behalf to the right party, requesting the missing details. When the response arrives, FAB updates your books automatically.",
    "about.different.item2.title": "Privacy by Design",
    "about.different.item2.desc": "FAB is installed locally on your device. Your financial data never leaves your computer unless you explicitly choose to sync. End-to-end encryption protects all data in transit, and biometric login ensures only you can access your information.",
    "about.different.item3.title": "Built for the Dutch System",
    "about.different.item3.desc": "FAB understands PGB, WLZ, WMO, Wajong, and WIA. It knows how earmarked healthcare funds work, which payments can only come from specific sources, and how to track the complete journey of every euro through the Dutch healthcare financial system.",
    "about.different.item4.title": "Designed for Real People",
    "about.different.item4.desc": "We built FAB for individuals who are already managing the demands of chronic illness or disability. That is why it requires less than 10 minutes per week. The AI handles the heavy lifting — you only review what the system is uncertain about.",
    "about.values.subtitle": "Principles That",
    "about.values.subtitleHighlight": "Guide Everything",
    "about.values.subtitleEnd": "We Build",
    "about.values.v1.title": "Empathy First",
    "about.values.v1.desc": "Every feature we build starts with the question: does this reduce the burden on someone who is already managing more than most?",
    "about.values.v2.title": "Radical Transparency",
    "about.values.v2.desc": "Your data is yours. We believe in complete transparency about how your information is processed, stored, and protected.",
    "about.values.v3.title": "Automation with Trust",
    "about.values.v3.desc": "AI should work for you, not replace your judgment. FAB automates the tedious work but always gives you the final say on uncertain decisions.",
    "about.values.v4.title": "Clarity Over Complexity",
    "about.values.v4.desc": "We do not add features for the sake of features. Every element in FAB exists to bring you closer to understanding your true financial picture.",
    "about.impact.biggerPicture": "The Bigger Picture",
    "about.impact.title1": "Revealing the",
    "about.impact.titleHighlight": "True Cost",
    "about.impact.titleEnd": "of Disability",
    "about.impact.p1": "Beyond helping individuals, FAB has a broader social mission. Today, there is no comprehensive data on what chronic illness and disability truly cost a person compared to their healthy peers. The hidden expenses — specialized equipment, home modifications, dietary needs, additional transportation, lost earning potential — remain invisible in public policy discussions.",
    "about.impact.p2": "With the consent of our users, FAB can aggregate anonymized financial data to produce the first population-scale evidence of the disability cost premium. This data can inform policy makers, advocacy organizations, and healthcare institutions about the real financial burden that individuals with disabilities carry every day.",
    "about.impact.p3": "We live in a time where even individuals with significant health challenges are forced to maintain side-hustles to cover unrecoupable costs. FAB not only helps manage that reality — it helps make it visible so that, one day, it can change.",
    "about.impact.stat1": "Dutch Disability Benefit Recipients",
    "about.impact.stat1Detail": "Over one million people in the Netherlands receive PGB, Wajong, or WIA benefits — each managing complex financial ecosystems.",
    "about.impact.stat2": "Annual PGB Expenditure",
    "about.impact.stat2Detail": "Billions of euros flow through the PGB system annually, managed by individuals who often lack the tools to track it properly.",
    "about.impact.stat3": "Extra Living Costs",
    "about.impact.stat3Detail": "Research shows people with disabilities face 30% or more in additional living costs compared to their non-disabled peers.",
    "about.vision.label": "Our Vision",
    "about.vision.title1": "A World Where Health Conditions",
    "about.vision.titleHighlight": "Do Not Define",
    "about.vision.titleEnd": "Financial Outcomes",
    "about.vision.p1": "We envision a future where no one has to choose between managing their health and managing their finances. Where the true cost of disability is visible, acknowledged, and addressed. Where technology serves as a bridge to financial independence, not another barrier to overcome.",
    "about.vision.p2": "Starting in the Netherlands, FAB will expand to serve individuals with complex health-related finances across Europe and beyond. Because the need for financial clarity is universal, even if the systems that create the complexity are local.",

    // FAQ page
    "faq.badge": "Frequently Asked Questions",
    "faq.title1": "Everything You Need",
    "faq.titleHighlight": "to Know",
    "faq.desc": "Find answers to common questions about FAB, from data privacy and PGB integration to our pricing model and autonomous features.",
    "faq.search": "Search for a question...",
    "faq.results": "results",
    "faq.noResults": "No results found",
    "faq.noResultsDesc": "Try different keywords or browse the categories below.",
    "faq.clear": "Clear",
    "faq.cta.title": "Still Have Questions?",
    "faq.cta.desc": "Our team is here to help. Reach out and we'll get back to you within 24 hours.",
    "faq.cta.primary": "Ask a Question",
    "faq.cta.secondary": "How It Works",
    "faq.categories": "Categories",
    "faq.questions": "questions",
    "faq.result": "result",
    "faq.askDirectly": "Ask Us Directly",
    "faq.sidebarDesc": "Our team understands the unique challenges of managing disability-related finances.",
    "faq.contactUs": "Contact Us",
    "faq.cat.general": "General",
    "faq.cat.general.desc": "Learn the basics about FAB and what it does",
    "faq.cat.privacy": "Data Privacy & Security",
    "faq.cat.privacy.desc": "How we protect your sensitive financial data",
    "faq.cat.pgb": "PGB Integration",
    "faq.cat.pgb.desc": "How FAB works with the Dutch PGB system",
    "faq.cat.pricing": "Pricing & Billing",
    "faq.cat.pricing.desc": "Understanding our fair, usage-based pricing",
    "faq.cat.autonomous": "Autonomous Features",
    "faq.cat.autonomous.desc": "How FAB's AI works on your behalf",
    "faq.cat.technical": "Technical & Setup",
    "faq.cat.technical.desc": "Getting started and technical details",

    // Waitlist
    "waitlist.badge": "Early Access",
    "waitlist.title": "Be the First to Experience FAB",
    "waitlist.desc": "Join our waitlist to get early access when we launch. We'll keep you updated on our progress.",
    "waitlist.email": "Email address",
    "waitlist.emailPlaceholder": "you@example.com",
    "waitlist.name": "Full name",
    "waitlist.namePlaceholder": "Your name",
    "waitlist.situation": "Your situation",
    "waitlist.situationPlaceholder": "Select your situation",
    "waitlist.situationPGB": "PGB holder",
    "waitlist.situationWajong": "Wajong recipient",
    "waitlist.situationWIA": "WIA recipient",
    "waitlist.situationCaregiver": "Caregiver / family member",
    "waitlist.situationOther": "Other",
    "waitlist.submit": "Join Waitlist",
    "waitlist.submitting": "Joining...",
    "waitlist.success.title": "You're on the list!",
    "waitlist.success.desc": "Thank you for your interest in FAB. We'll notify you as soon as early access is available.",
    "waitlist.success.close": "Close",
    "waitlist.success.alreadyTitle": "You're already on the list!",
    "waitlist.success.alreadyDesc": "This email is already registered. We'll notify you as soon as early access is available.",
    "waitlist.privacy": "We respect your privacy. No spam, ever.",

    // How It Works page
    "hiwPage.badge": "How FAB Works",
    "hiwPage.title1": "Your Journey from",
    "hiwPage.titleHighlight": "Chaos to Clarity",
    "hiwPage.desc": "A detailed walkthrough of how FAB transforms scattered financial data into structured, actionable insights — automatically.",
    "hiwPage.step": "Step",
    "hiwPage.stepOne": "Step One",
    "hiwPage.step1.title": "Connect & Manage Your Platforms",
    "hiwPage.step1.desc": "FAB doesn't just read your data — it actively manages your accounts on MijnGeldzaken.nl, WaveApps, SVB, and your bank. Through a simple onboarding wizard, you authorize FAB to securely access and operate your accounts using OAuth. FAB becomes your financial command center, orchestrating actions across all platforms so you never have to log in separately.",
    "hiwPage.step1.gmail": "Invoices, receipts, and financial confirmations from your inbox.",
    "hiwPage.step1.whatsapp": "Photos of receipts, payment confirmations, and vendor messages.",
    "hiwPage.step1.drive": "Scanned documents, spreadsheets, and financial records.",
    "hiwPage.step1.bank": "Direct transaction feeds via PSD2 open banking APIs.",
    "hiwPage.step1.mgz": "FAB logs in, creates entries, and keeps your household administration up to date automatically.",
    "hiwPage.step1.wave": "FAB manages your business books and health expense tracking — creating invoices, categorizing transactions, and reconciling accounts.",
    "hiwPage.step1.svb": "FAB handles PGB declarations, tracks budget usage, and manages care worker payment submissions.",
    "hiwPage.step1.cash": "Manual input or photo scanning of cash receipts via mobile.",
    "hiwPage.step1.secure": "Secure by Design",
    "hiwPage.step1.secureDesc": "All connections use OAuth 2.0 or PSD2-compliant APIs. Your credentials are never stored. Data is encrypted end-to-end and stored locally on your device.",
    "hiwPage.stepTwo": "Step Two",
    "hiwPage.step2.title": "AI Extracts & Categorizes",
    "hiwPage.step2.desc": "Once connected, FAB's AI engine goes to work. It scans every source, extracts financial data using advanced OCR and natural language processing, and intelligently categorizes each transaction.",
    "hiwPage.step2.scan": "Scan",
    "hiwPage.step2.scanTitle": "Document Scanning",
    "hiwPage.step2.scanDesc": "OCR reads receipts, invoices, and statements — extracting amounts, dates, vendors, and descriptions.",
    "hiwPage.step2.classify": "Classify",
    "hiwPage.step2.classifyTitle": "AI Classification",
    "hiwPage.step2.classifyDesc": "Machine learning categorizes each transaction: household, healthcare, side-hustle, or earmarked PGB funds.",
    "hiwPage.step2.map": "Map",
    "hiwPage.step2.mapTitle": "Source Mapping",
    "hiwPage.step2.mapDesc": "Each transaction is mapped to its income source or expenditure destination based on your defined rules.",
    "hiwPage.step2.score": "Score",
    "hiwPage.step2.scoreTitle": "Confidence Scoring",
    "hiwPage.step2.scoreDesc": "Every classification gets a confidence score. High-confidence items proceed automatically; uncertain ones are flagged.",
    "hiwPage.step2.extractTitle": "What the AI Extracts from Each Document",
    "hiwPage.step2.vendorName": "Vendor Name",
    "hiwPage.step2.vendorEx": "Albert Heijn, Apotheek, etc.",
    "hiwPage.step2.amount": "Amount",
    "hiwPage.step2.amountEx": "€47.50, €125.00, etc.",
    "hiwPage.step2.date": "Date",
    "hiwPage.step2.dateEx": "2026-03-01, etc.",
    "hiwPage.step2.category": "Category",
    "hiwPage.step2.categoryEx": "Healthcare, Household, etc.",
    "hiwPage.step2.invoice": "Invoice Number",
    "hiwPage.step2.invoiceEx": "INV-2026-0042",
    "hiwPage.step2.payment": "Payment Method",
    "hiwPage.step2.paymentEx": "iDEAL, Cash, Card",
    "hiwPage.step2.taxDeduct": "Tax Deductible",
    "hiwPage.step2.taxDeductEx": "Yes / No",
    "hiwPage.step2.earmarked": "Earmarked Fund",
    "hiwPage.step2.earmarkedEx": "PGB, WLZ, WMO",
    "hiwPage.stepThree": "Step Three",
    "hiwPage.step3.title": "Auto-Route, Manage & Sync",
    "hiwPage.step3.desc": "This is where FAB truly shines. Processed transactions are automatically routed to the correct platform — and FAB logs into each one to create entries, update records, and keep everything synchronized. Missing data? FAB emails vendors on your behalf to fill in the blanks.",
    "hiwPage.step3.routing": "Intelligent Routing",
    "hiwPage.step3.r1from": "Household expenses",
    "hiwPage.step3.r1to": "mijngeldzaken.nl",
    "hiwPage.step3.r2from": "Side-hustle income/expenses",
    "hiwPage.step3.r2to": "WaveApps (Business)",
    "hiwPage.step3.r3from": "Health-related costs",
    "hiwPage.step3.r3to": "WaveApps (Personal)",
    "hiwPage.step3.r4from": "PGB care worker payments",
    "hiwPage.step3.r4to": "SVB",
    "hiwPage.step3.routingNote": "Each platform is an 'end station' — money and data flow into them but not between them. FAB tracks the complete journey of each euro to prevent double-counting.",
    "hiwPage.step3.autoComplete": "Autonomous Data Completion",
    "hiwPage.step3.ac1": "Gap Detection",
    "hiwPage.step3.ac1Desc": "FAB scans the books and identifies entries with missing vendor name, amount, date, or invoice number.",
    "hiwPage.step3.ac2": "Contact Identification",
    "hiwPage.step3.ac2Desc": "Using existing data clues, FAB determines which party to contact for the missing information.",
    "hiwPage.step3.ac3": "Email Drafting",
    "hiwPage.step3.ac3Desc": "A professional email is crafted using a standard template, requesting the specific missing details.",
    "hiwPage.step3.ac4": "User Approval",
    "hiwPage.step3.ac4Desc": "You review and approve the email before it's sent from your inbox. Full control, always.",
    "hiwPage.step3.ac5": "Response Processing",
    "hiwPage.step3.ac5Desc": "When the vendor responds, FAB parses the reply and auto-updates the book entry.",
    "hiwPage.step3.ac6": "Follow-Up",
    "hiwPage.step3.ac6Desc": "If no response within your set timeframe, FAB sends a follow-up (up to your configured max attempts).",
    "hiwPage.step3.sync": "Continuous Synchronization",
    "hiwPage.step3.syncDesc": "FAB continuously syncs with all your platforms to keep everything up to date. You control the frequency with simple sliders for each operation type.",
    "hiwPage.step3.syncPlatform": "Platform Sync",
    "hiwPage.step3.syncPlatformFreq": "Every hour",
    "hiwPage.step3.syncPlatformDesc": "Pull new data from mijngeldzaken.nl, WaveApps, SVB, and bank accounts.",
    "hiwPage.step3.syncSource": "Source Scanning",
    "hiwPage.step3.syncSourceFreq": "Every hour",
    "hiwPage.step3.syncSourceDesc": "Check Gmail, WhatsApp, and Google Drive for new financial documents.",
    "hiwPage.step3.syncData": "Data Completion",
    "hiwPage.step3.syncDataFreq": "Every 5 minutes",
    "hiwPage.step3.syncDataDesc": "Check for vendor email responses and auto-update incomplete entries.",
    "hiwPage.step3.adjustable": "Adjustable via settings",
    "hiwPage.stepFour": "Step Four",
    "hiwPage.step4.title": "Review & Relax",
    "hiwPage.step4.desc": "Every week, you spend less than 10 minutes reviewing only what the AI is uncertain about. Everything else has been handled automatically. Here's what your weekly review looks like:",
    "hiwPage.step4.queue": "Your Weekly Review Queue",
    "hiwPage.step4.queueNote": "Only 3 items this week need your attention. The other 47 transactions were processed automatically.",
    "hiwPage.step4.unknownVendor": "Unknown Vendor",
    "hiwPage.step4.vendorName": "Vendor name",
    "hiwPage.step4.healthcare": "Healthcare?",
    "hiwPage.step4.categoryLabel": "Category",
    "hiwPage.step4.healthHousehold": "Healthcare / Household?",
    "hiwPage.step4.householdSide": "Household / Side-hustle?",
    "hiwPage.step4.summary": "This Week's Summary",
    "hiwPage.step4.autoProcessed": "transactions auto-processed",
    "hiwPage.step4.needReview": "items need your review",
    "hiwPage.step4.totalProcessed": "total processed this week",
    "hiwPage.step4.healthCosts": "healthcare costs identified",
    "hiwPage.step4.timeSaved": "Time Saved",
    "hiwPage.step4.hoursWeek": "hours this week",
    "hiwPage.step4.compared": "Compared to manual bookkeeping",
    "hiwPage.flow.label": "The Complete Picture",
    "hiwPage.flow.title": "End-to-End Data Flow",
    "hiwPage.flow.desc": "From scattered documents to structured clarity — here's the complete journey of your financial data through FAB.",
    "hiwPage.flow.sources": "Data Sources",
    "hiwPage.flow.engine": "FAB Processing Engine",
    "hiwPage.flow.endStations": "End-Station Platforms",
    "hiwPage.flow.household": "Household",
    "hiwPage.flow.sideHustle": "Side-Hustle",
    "hiwPage.flow.healthcareType": "Healthcare",
    "hiwPage.flow.pgbPayments": "PGB Payments",
    "hiwPage.flow.result": "Result",
    "hiwPage.flow.resultTitle": "Complete Financial Clarity",
    "hiwPage.flow.resultDesc": "Unified view across all platforms with healthcare cost quantification",
    "hiwPage.flow.ocrExtraction": "OCR Extraction",
    "hiwPage.flow.aiClassification": "AI Classification",
    "hiwPage.flow.sourceMapping": "Source Mapping",
    "hiwPage.flow.confidenceScoring": "Confidence Scoring",
    "hiwPage.flow.gapDetection": "Gap Detection",
    "hiwPage.flow.autoEmail": "Auto-Email",

    // Footer legal items
    "footer.legal.privacypolicy": "Privacy Policy",
    "footer.legal.termsofservice": "Terms of Service",
    "footer.legal.gdpr": "GDPR",
    "footer.legal.cookiepolicy": "Cookie Policy",

    // Payment pages
    "payment.verifying": "Verifying your payment...",
    "payment.success.title": "Usage billing ready",
    "payment.success.desc": "Your payment method is ready for verified usage invoices. FAB charges resource cost x 2.5 and has no fixed monthly fee.",
    "payment.success.emailNote": "Billing contact",
    "payment.success.cta": "Go to Dashboard",
    "payment.error.title": "Something Went Wrong",
    "payment.error.desc": "We couldn't verify your payment. If you believe this is an error, please contact our support team.",
    "payment.error.cta": "Contact Support",
    "payment.cancel.title": "Payment Cancelled",
    "payment.cancel.desc": "No worries — you can always come back and subscribe when you're ready. Your data is safe with us.",
    "payment.cancel.cta": "Back to Home",

    // Account page
    "account.title": "My Account",
    "account.welcome": "Welcome back",
    "account.user": "User",
    "account.subtitle": "Manage usage billing, invoices, and account settings.",
    "account.loginRequired": "Sign In Required",
    "account.loginRequiredDesc": "Please sign in to access your account settings and subscription details.",
    "account.profile": "Profile",
    "account.logout": "Sign Out",
    "account.name": "Name",
    "account.email": "Email",
    "account.memberSince": "Member Since",
    "account.plan": "Current Plan",
    "account.freePlan": "Free Plan",
    "account.subscription": "Usage billing",
    "account.statusActive": "Active",
    "account.statusTrialing": "Trial",
    "account.statusPastDue": "Past Due",
    "account.statusCanceled": "Canceled",
    "account.statusFree": "Free",
    "account.currentPeriodEnd": "Current Period Ends",
    "account.autoRenew": "Auto-Renewal",
    "account.cancelAtEnd": "Cancels at period end",
    "account.autoRenewYes": "Enabled",
    "account.manageBilling": "Manage Billing",
    "account.portalRedirect": "Opening billing portal...",
    "account.checkoutRedirect": "Redirecting to checkout...",
    "account.freePlanTitle": "You're on the Free Plan",
    "account.freePlanDesc": "Upgrade to Pay-As-You-Go for unlimited document processing, multi-bank connections, and priority support.",
    "account.upgradeCta": "Upgrade to Pay-As-You-Go",
    "account.invoices": "Invoice History",
    "account.noInvoices": "No invoices yet. Your invoices will appear here once you subscribe.",
    "account.invoiceDate": "Date",
    "account.invoiceAmount": "Amount",
    "account.invoiceStatus": "Status",
    "account.invoiceActions": "Actions",
    "account.viewInvoice": "View Invoice",
    "account.downloadPdf": "Download PDF",
    "nav.account": "Account",

    // Legal layout
    "legal.backHome": "Back to Home",
    "legal.lastUpdated": "Last updated",
  },

  nl: {
    // Navbar
    "nav.howItWorks": "Hoe Het Werkt",
    "nav.features": "Functies",
    "nav.security": "Beveiliging",
    "nav.pricing": "Prijzen",
    "nav.impact": "Impact",
    "nav.about": "Over Ons",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "nav.blog": "Blog",
    "nav.home": "Home",
    "nav.signIn": "Inloggen",
    "nav.getStarted": "Aan de Slag",

    // Hero
    "hero.badge": "Financiële Helderheid voor Iedereen",
    "hero.title1": "Breng Structuur &",
    "hero.titleHighlight": "Helderheid",
    "hero.title2": "in Je Financiën",
    "hero.desc": "FAB is een intelligent financieel orkestratieplatform dat je boekhouding automatiseert, je bestaande tools verbindt en je een compleet beeld geeft van je financiën — in minder dan 10 minuten per week.",
    "hero.cta1": "Gratis Beginnen",
    "hero.cta2": "Bekijk Hoe Het Werkt",
    "hero.stat1": "<10 min/week",
    "hero.stat2": "E2E Versleuteld",
    "hero.stat3": "Desktop & Mobiel",

    // Problem
    "problem.label": "De Uitdaging",
    "problem.title": "Financiën Beheren Hoeft Geen Fulltime Baan Te Zijn",
    "problem.desc": "Voor mensen met een beperking of chronische ziekte is de financiële administratie verspreid over WhatsApp-berichten, e-mailinboxen, Google Drive-mappen en meerdere platforms. Deze chaos kost uren per week — tijd die beter besteed kan worden aan gezondheid en welzijn.",
    "problem.card1.title": "Verspreide Documenten",
    "problem.card1.desc": "Bonnetjes in WhatsApp, facturen in Gmail, afschriften in Drive. Geen enkele bron van waarheid voor je financiën.",
    "problem.card1.stat": "5+",
    "problem.card1.statLabel": "databronnen",
    "problem.card2.title": "Uren Handmatig Werk",
    "problem.card2.desc": "Handmatig transacties invoeren, leveranciers achterna zitten voor ontbrekende informatie, afstemmen tussen platforms.",
    "problem.card2.stat": "4-8",
    "problem.card2.statLabel": "uur per week",
    "problem.card3.title": "Verborgen Zorgkosten",
    "problem.card3.desc": "De werkelijke financiële impact van een beperking blijft onzichtbaar — verspreid over geoormerkte fondsen, verzekeringen en eigen bijdragen.",
    "problem.card3.stat": "€17K+",
    "problem.card3.statLabel": "extra jaarlijkse kosten",

    // How It Works
    "hiw.label": "Hoe Het Werkt",
    "hiw.title": "Van Chaos naar Helderheid in Vier Stappen",
    "hiw.desc": "FAB werkt stil op de achtergrond en transformeert verspreide financiële gegevens naar gestructureerde, bruikbare helderheid.",
    "hiw.step1.title": "Verbind & Beheer Je Platforms",
    "hiw.step1.desc": "Autoriseer FAB om je accounts te beheren op MijnGeldzaken.nl, WaveApps, SVB, banken, Gmail en meer.",
    "hiw.step2.title": "AI Extraheert & Categoriseert",
    "hiw.step2.desc": "Onze AI scant je bronnen, extraheert financiële gegevens met OCR en categoriseert elke transactie intelligent.",
    "hiw.step3.title": "Auto-Routeren & Beheren",
    "hiw.step3.desc": "FAB logt in op elk platform om boekingen aan te maken, records bij te werken en alles gesynchroniseerd te houden. Ontbrekende gegevens? FAB e-mailt leveranciers namens jou.",
    "hiw.step4.title": "Controleren & Ontspannen",
    "hiw.step4.desc": "Besteed minder dan 10 minuten per week aan het beoordelen van alleen wat de AI onzeker over is. De rest wordt afgehandeld.",

    // Features
    "features.orch.label": "Intelligente Orkestratie",
    "features.orch.title": "Eén Platform, Al Je Financiële Tools",
    "features.orch.desc": "FAB verbindt met mijngeldzaken.nl, WaveApps, SVB en je bankrekeningen — transacties ophalen, versturen en bijwerken op alle platforms in real-time.",
    "features.orch.item1": "Bidirectionele synchronisatie met alle platforms",
    "features.orch.item2": "Geoormerkte fondsen mapping voor PGB",
    "features.orch.item3": "Synchronisatiecycli per uur",
    "features.orch.item4": "Conflictdetectie en -oplossing",
    "features.ai.label": "AI-Aangedreven Verwerking",
    "features.ai.title": "Zelfaanvullende, Zelfherstellende Boeken",
    "features.ai.desc": "FAB's AI categoriseert niet alleen — het identificeert ontbrekende gegevens, stelt professionele e-mails op naar leveranciers en werkt je boeken automatisch bij wanneer antwoorden binnenkomen.",
    "features.ai.item1": "OCR-scanning van bonnetjes en facturen",
    "features.ai.item2": "Autonome leverancierscommunicatie",
    "features.ai.item3": "Op vertrouwen gebaseerd markeringssysteem",
    "features.ai.item4": "Continu leren van correcties",
    "features.dash.label": "Unified Dashboard",
    "features.dash.title": "Bekijk Je Volledige Financiële Beeld",
    "features.dash.desc": "Zie voor het eerst al je financiën op één plek — huishoudelijke uitgaven, bijverdiensten, zorgkosten en geoormerkte fondsen. FAB kwantificeert je werkelijke \"beperkingskostenpremie\" en identificeert automatisch aftrekbare kosten.",
    "features.dash.item1": "Real-time kostendashboard",
    "features.dash.item2": "Zorgkostenrapportages",
    "features.dash.item3": "Jaarlijkse belastingoverzichten",
    "features.dash.item4": "Exporteren in universele formaten (CSV, PDF)",

    // Integrations
    "integrations.label": "Verbonden Platforms",
    "integrations.title": "FAB Beheert Je Bestaande Tools",
    "integrations.desc": "FAB is niet zomaar een financiële app. Het is een orkestratielaag die verbindt met de platforms die je al gebruikt — inloggen, boekingen aanmaken, records bijwerken en alles gesynchroniseerd houden over je hele financiële ecosysteem.",
    "integrations.mgz.title": "MijnGeldzaken.nl",
    "integrations.mgz.desc": "FAB logt in op je MijnGeldzaken-account, maakt huishoudboekingen aan, categoriseert transacties en onderhoudt je complete huishoudelijke financiële administratie — automatisch.",
    "integrations.mgz.tag": "Huishoudfinanciën",
    "integrations.wave.title": "Wave Apps",
    "integrations.wave.desc": "FAB beheert je Wave-boekhouding — facturen aanmaken, uitgaven registreren, banktransacties afstemmen en aparte boeken bijhouden voor zakelijke en zorgkosten.",
    "integrations.wave.tag": "Boekhouding",
    "integrations.banks.title": "Nederlandse Banken",
    "integrations.banks.desc": "Directe PSD2 open banking-verbindingen met ING, ABN AMRO, Rabobank en meer. FAB haalt transactiefeeds op in real-time en koppelt ze aan je boekhouding.",
    "integrations.banks.tag": "Bankieren",
    "integrations.svb.title": "SVB (Sociale Verzekeringsbank)",
    "integrations.svb.desc": "FAB handelt je PGB-declaraties af, volgt budgetgebruik, dient betalingsverzoeken voor zorgverleners in en monitort goedkeuringsstatussen — allemaal binnen je SVB-account.",
    "integrations.svb.tag": "PGB-Beheer",
    "integrations.google.title": "Gmail & Google Drive",
    "integrations.google.desc": "FAB scant je inbox op facturen en bonnen, monitort Drive-mappen op financiële documenten en verwerkt automatisch alles wat het vindt.",
    "integrations.google.tag": "Documentbronnen",
    "integrations.more.title": "Meer Integraties Komen Eraan",
    "integrations.more.desc": "We breiden continu onze platformverbindingen uit. WhatsApp Business, Exact Online, Moneybird en meer staan op onze roadmap.",
    "integrations.more.tag": "Roadmap",
    "integrations.callout.title": "Niet alleen verbinden — actief beheren",
    "integrations.callout.desc": "In tegenstelling tot traditionele aggregators die alleen je gegevens lezen, voert FAB bidirectionele operaties uit. Het logt in op MijnGeldzaken.nl om boekingen te maken, beheert je Wave-facturen en dient PGB-declaraties in bij SVB — allemaal georkestreerd vanuit één intelligent platform.",
    "integrations.cta": "Bekijk Hoe Het Werkt",

    // Stats
    "stats.users": "Potentiële Gebruikers in NL",
    "stats.usersSub": "PGB, Wajong & WIA ontvangers",
    "stats.budget": "PGB Budget Beheerd",
    "stats.budgetSub": "Jaarlijks door SVB",
    "stats.minutes": "Minuten Per Week",
    "stats.minutesSub": "Benodigde gebruikerstijd",
    "stats.saved": "Tijd Bespaard",
    "stats.savedSub": "Op financiële administratie",

    // Testimonials
    "testimonials.label": "Wat Mensen Zeggen",
    "testimonials.title": "Vertrouwd door Vroege Gebruikers",
    "testimonials.desc": "Hoor van de mensen die FAB uit eerste hand hebben ervaren tijdens ons vroege toegangsprogramma.",
    "testimonials.t1.quote": "FAB heeft compleet veranderd hoe ik mijn PGB beheer. Wat me vroeger 6 uur per week kostte, gebeurt nu automatisch. Ik heb eindelijk tijd voor wat echt telt — mijn gezondheid.",
    "testimonials.t1.name": "Sarah M.",
    "testimonials.t1.role": "PGB-houder, Amsterdam",
    "testimonials.t2.quote": "Als mantelzorger voor mijn moeder verdronk ik in papierwerk. FAB bracht alles samen op één plek. De AI-categorisering is opmerkelijk nauwkeurig.",
    "testimonials.t2.name": "Thomas K.",
    "testimonials.t2.role": "Mantelzorger, Utrecht",
    "testimonials.t3.quote": "Ik was sceptisch over weer een financiële app, maar FAB is anders. Het begrijpt echt het Nederlandse zorgsysteem. Alleen al de WMO-integratie bespaarde me uren.",
    "testimonials.t3.name": "Lisa van D.",
    "testimonials.t3.role": "WIA-ontvanger, Rotterdam",
    "testimonials.t4.quote": "De privacy-first aanpak overtuigde me. Mijn financiële gegevens blijven op mijn apparaat, en de end-to-end encryptie geeft me echte gemoedsrust. Zo hoort fintech te werken.",
    "testimonials.t4.name": "Mark B.",
    "testimonials.t4.role": "Financieel Adviseur, Den Haag",
    "testimonials.trustBadge1": "Privacy Eerst",
    "testimonials.trustBadge2": "AVG-Conform",
    "testimonials.trustBadge3": "Nederlands Gebouwd",
    "testimonials.trustBadge4": "Open Source Kern",

    // Blog / Updates
    "blog.label": "Laatste Updates",
    "blog.title": "Nieuws & Inzichten",
    "blog.desc": "Blijf op de hoogte van FAB's ontwikkelingsreis, productmijlpalen en inzichten over financiële toegankelijkheid.",
    "blog.readMore": "Lees Meer",
    "blog.viewAll": "Bekijk Alle Updates",
    "blog.backToBlog": "Terug naar Blog",
    "blog.publishedOn": "Gepubliceerd op",
    "blog.minRead": "min lezen",
    "blog.noPosts": "Nog geen berichten. Kom snel terug!",
    "blog.pageTitle": "Blog & Updates",
    "blog.pageDesc": "Productmijlpalen, functievoorbeelden en inzichten over het toegankelijk maken van financieel beheer voor iedereen.",
    "blog.badge": "Blog & Updates",
    "blog.searchPlaceholder": "Zoek artikelen...",
    "blog.allPosts": "Alle Berichten",
    "blog.catUpdate": "Update",
    "blog.catMilestone": "Mijlpaal",
    "blog.catFeature": "Functie",
    "blog.catAnnouncement": "Aankondiging",
    "blog.catTechnology": "Technologie",
    "blog.catGuide": "Gids",
    "blog.noPostsDesc": "We werken aan nieuwe inhoud. Kom snel terug voor updates over de ontwikkeling van FAB.",
    "blog.readTime": "lezen",
    "blog.postNotFound": "Bericht Niet Gevonden",
    "blog.postNotFoundDesc": "Het blogbericht dat je zoekt bestaat niet of is verwijderd.",
    "blog.ctaTitle": "Vond je dit artikel leuk?",
    "blog.ctaDesc": "Ontdek meer updates en inzichten over de reis van FAB.",
    "blog.ctaButton": "Bekijk Alle Berichten",

    // Security
    "security.label": "Privacy & Beveiliging",
    "security.title": "Je Gegevens Blijven Van Jou",
    "security.desc": "FAB is gebouwd met privacy als kern. Je financiële gegevens worden lokaal op je apparaat opgeslagen, beschermd door end-to-end encryptie en volledig conform Nederlandse en EU-regelgeving.",
    "security.e2e": "E2E Encryptie",
    "security.e2eDesc": "Alle gegevens versleuteld tijdens transport en opslag",
    "security.gdpr": "AVG Conform",
    "security.gdprDesc": "Volledige naleving van Nederlandse AP-regelgeving",
    "security.bio": "Biometrische Login",
    "security.bioDesc": "Vingerafdruk- en gezichtsherkenning",
    "security.export": "Gegevensexport",
    "security.exportDesc": "Exporteer of verwijder al je gegevens op elk moment",
    "security.local": "Lokaal geïnstalleerd — gegevens verlaten nooit je apparaat",
    "security.2fa": "Tweefactorauthenticatie (2FA)",
    "security.emailApproval": "E-mailgoedkeuring vóór autonome verzendingen",
    "security.offline": "Werkt volledig offline — synchroniseert bij verbinding",
    "security.gdprExport": "AVG-gegevensexport en permanente verwijdering",
    "security.trusted": "Vertrouwenspersoon alleen-lezen toegang",

    // Pricing
    "pricing.label": "Prijzen",
    "pricing.title": "Betaal Alleen Wat Je Gebruikt",
    "pricing.desc": "FAB gebruikt een transparant, op gebruik gebaseerd prijsmodel. Je betaalt alleen voor de resources die je verbruikt — geen verborgen kosten, geen verrassingen.",
    "pricing.free.label": "Gratis",
    "pricing.free.price": "€0",
    "pricing.free.period": "/altijd",
    "pricing.free.desc": "Begin en ervaar de kernwaarde van FAB.",
    "pricing.free.item1": "3 transacties per week",
    "pricing.free.item2": "Alle platformintegraties",
    "pricing.free.item3": "AI-categorisatie",
    "pricing.free.item4": "Basisrapportages",
    "pricing.free.item5": "Desktop & mobiel toegang",
    "pricing.free.cta": "Gratis Starten",
    "pricing.payg.label": "Betaal Per Gebruik",
    "pricing.payg.formula": "Gebruik × 2,5",
    "pricing.payg.desc": "Eerlijke, transparante prijzen op basis van daadwerkelijk gebruik.",
    "pricing.payg.item1": "Onbeperkte transacties",
    "pricing.payg.item2": "Autonome gegevensaanvulling",
    "pricing.payg.item3": "Volledige e-mailautomatisering",
    "pricing.payg.item4": "Geavanceerde rapportages & belastingoverzichten",
    "pricing.payg.item5": "Real-time kostendashboard",
    "pricing.payg.item6": "Instelbare bestedingslimiet",
    "pricing.payg.item7": "Prioriteitsondersteuning",
    "pricing.payg.cta": "Aan de Slag",

    // Impact
    "impact.label": "Maatschappelijke Impact",
    "impact.title": "De Werkelijke Kosten van een Beperking Meten",
    "impact.desc": "FAB is meer dan een financiële tool. Door geanonimiseerde gegevens te aggregeren, kunnen we unieke rapporten publiceren over de werkelijke financiële last van leven met een beperking — bewijs voor beter beleid en ondersteuning.",
    "impact.card1.title": "Financiële Empowerment",
    "impact.card1.desc": "Geef tijd en energie terug aan mensen die het het meest nodig hebben.",
    "impact.card2.title": "Kostentransparantie",
    "impact.card2.desc": "Kwantificeer de werkelijke 'beperkingskostenpremie' op bevolkingsschaal.",
    "impact.card3.title": "Beleidsbewijs",
    "impact.card3.desc": "Geanonimiseerde gegevens voor beter beperkingsbeleid en ondersteuning.",
    "impact.card4.title": "Gemeenschapskracht",
    "impact.card4.desc": "Bouw een netwerk van empowered individuen die hun financiële realiteit begrijpen.",

    // CTA
    "cta.title": "Klaar om Helderheid in Je Financiën te Brengen?",
    "cta.desc": "Sluit je aan bij de beweging naar financiële empowerment. Begin met 3 gratis transacties per week en ervaar het verschil.",
    "cta.primary": "Gratis Beginnen",
    "cta.secondary": "Neem Contact Op",

    // Footer
    "footer.desc": "Financiële Structuur & Helderheid voor mensen die complexe gezondheidsgerelateerde financiën beheren in Nederland.",
    "footer.product": "Product",
    "footer.company": "Bedrijf",
    "footer.legal": "Juridisch",
    "footer.rights": "Alle rechten voorbehouden.",
    "footer.madeWith": "Gemaakt met",
    "footer.inNL": "in Nederland",

    // Contact page
    "contact.badge": "Neem Contact Op",
    "contact.title1": "Laten We een",
    "contact.titleHighlight": "Gesprek",
    "contact.desc": "Heb je vragen over FAB? Wil je weten hoe we helderheid in je financiën kunnen brengen? We horen graag van je.",
    "contact.form.firstName": "Voornaam",
    "contact.form.lastName": "Achternaam",
    "contact.form.email": "E-mailadres",
    "contact.form.topic": "Onderwerp",
    "contact.form.topicPlaceholder": "Selecteer een onderwerp",
    "contact.form.message": "Bericht",
    "contact.form.messagePlaceholder": "Vertel ons hoe we je kunnen helpen...",
    "contact.form.send": "Bericht Versturen",
    "contact.form.sending": "Versturen...",
    "contact.success.title": "Bericht Verzonden!",
    "contact.success.desc": "Bedankt voor je bericht. We nemen binnen 24 uur contact met je op.",
    "contact.success.another": "Nog een Bericht Sturen",
    "contact.success.backHome": "Terug naar Home",
    "contact.success.toast": "Bericht succesvol verzonden!",
    "contact.info.email": "E-mail Ons",
    "contact.info.response": "Reactietijd",
    "contact.info.responseVal": "Binnen 24 uur",
    "contact.info.location": "Locatie",
    "contact.info.locationVal": "Nederland",
    "contact.info.phone": "Telefoon",
    "contact.info.phoneVal": "Plan een gesprek",
    "contact.info.faq": "Bekijk onze FAQ",
    "contact.info.faqDesc": "Bekijk onze veelgestelde vragen voor directe antwoorden op veelvoorkomende vragen over FAB's functies, prijzen en beveiliging.",
    "contact.info.faqLink": "Bezoek FAQ",
    "contact.topic.select": "Selecteer een onderwerp...",
    "contact.topic.general": "Algemene Vraag",
    "contact.topic.demo": "Demo Aanvragen",
    "contact.topic.pricing": "Prijzen & Pakketten",
    "contact.topic.partnership": "Samenwerkingsmogelijkheden",
    "contact.topic.support": "Technische Ondersteuning",
    "contact.topic.accessibility": "Toegankelijkheidsvraag",
    "contact.topic.media": "Media & Pers",
    "contact.error.firstName": "Voornaam is verplicht",
    "contact.error.lastName": "Achternaam is verplicht",
    "contact.error.email": "E-mail is verplicht",
    "contact.error.emailInvalid": "Voer een geldig e-mailadres in",
    "contact.error.subject": "Selecteer een onderwerp",
    "contact.error.message": "Bericht is verplicht",
    "contact.error.messageLength": "Bericht moet minimaal 10 tekens bevatten",
    "contact.toast.schedule": "Planningsfunctie binnenkort beschikbaar",
    "contact.form.firstNamePlaceholder": "Je voornaam",
    "contact.form.lastNamePlaceholder": "Je achternaam",
    "contact.form.emailPlaceholder": "jij@voorbeeld.nl",
    "contact.form.messagePlaceholderLong": "Vertel ons hoe we je kunnen helpen...",

    // FAQbout page
    "about.badge": "Ons Verhaal",
    "about.title1": "Geboren uit",
    "about.titleHighlight": "Geleefde Ervaring",
    "about.title2": "Gebouwd voor Echte Mensen",
    "about.mission.label": "Onze Missie",
    "about.mission.title": "Financiële Helderheid in Minder Dan 10 Minuten Per Week",
    "about.different.label": "Wat Ons Anders Maakt",
    "about.values.label": "Onze Waarden",
    "about.impact.label": "Onze Impactvisie",
    "about.cta.title": "Doe Mee aan het Bouwen van Financiële Helderheid",
    "about.cta.desc": "Of je nu een PGB-houder bent, een Wajong-ontvanger, of financiën beheert met een chronische aandoening — FAB is voor jou gebouwd.",
    "about.cta.primary": "Gratis Beginnen",
    "about.cta.secondary": "Neem Contact Op",
    "about.hero.desc": "FAB is niet bedacht in een bestuurskamer. Het is geboren uit de dagelijkse realiteit van het beheren van een huishouden terwijl je navigeert door de financiële complexiteit die komt met chronische ziekte en beperking. We begrijpen de strijd omdat we die zelf hebben meegemaakt.",
    "about.problem.title1": "Het Probleem",
    "about.problem.titleHighlight": "Dat We Leefden",
    "about.problem.p1": "Leven met een chronische ziekte of beperking in Nederland betekent navigeren door een doolhof van financiële verplichtingen. Je huishoudelijke uitgaven worden op één plek bijgehouden, je PGB-betalingen lopen via de SVB, je bijverdiensten staan in WaveApps, en belangrijke bonnetjes zijn verspreid over WhatsApp-berichten, Gmail-inboxen en Google Drive-mappen.",
    "about.problem.p2": "Het resultaat is financiële chaos. Uren per week besteed aan handmatig gegevens invoeren, ontbrekende bonnetjes achterna zitten en proberen accounts af te stemmen tussen platforms die nooit ontworpen zijn om met elkaar te communiceren. Uren die mensen met gezondheidsproblemen simpelweg niet hebben.",
    "about.problem.p3pre": "Erger nog, deze fragmentatie maakt het onmogelijk om een fundamentele vraag te beantwoorden:",
    "about.problem.p3quote": "Wat kost mijn ziekte of beperking mij werkelijk?",
    "about.problem.p3post": "Zonder dat antwoord is er geen helderheid, geen controle en geen pad naar financiële stabiliteit.",
    "about.mission.subtitle": "Financiële Structuur en Helderheid,",
    "about.mission.subtitleHighlight": "Zonder de Last",
    "about.mission.desc": "Onze missie is om mensen die complexe gezondheidsgerelateerde financiën beheren het ene te geven dat ze verdienen maar zelden hebben: volledige financiële helderheid met minimale inspanning. Wij geloven dat het beheren van je financiën minder dan 10 minuten per week moet kosten, niet 10 uur.",
    "about.mission.pillar1.title": "Automatiseer de Chaos",
    "about.mission.pillar1.desc": "FAB extraheert automatisch financiële gegevens uit WhatsApp, Gmail, Google Drive en foto's. Het categoriseert, vult de gaten en routeert elke transactie naar het juiste platform — zodat jij dat niet hoeft te doen.",
    "about.mission.pillar2.title": "Orkestreer Je Ecosysteem",
    "about.mission.pillar2.desc": "We vervangen je bestaande tools niet. FAB verbindt mijngeldzaken.nl, WaveApps, SVB en je bankrekeningen in één uniform, gesynchroniseerd systeem. Elke euro wordt gevolgd op zijn volledige reis.",
    "about.mission.pillar3.title": "Onthul de Werkelijke Kosten",
    "about.mission.pillar3.desc": "Voor het eerst kun je precies zien wat je gezondheidstoestand je kost. FAB kwantificeert de verborgen financiële last van een beperking — de kosten die gezonde mensen nooit tegenkomen.",
    "about.different.subtitle": "Niet Zomaar Weer Een",
    "about.different.subtitleHighlight": "Financiële App",
    "about.different.desc": "De meeste financiële tools vragen jou het werk te doen. FAB doet het werk voor je. Dit is wat ons onderscheidt.",
    "about.different.item1.title": "Zelfaanvullende Boeken",
    "about.different.item1.desc": "Wanneer FAB ontbrekende informatie vindt in je administratie — een leveranciersnaam, een factuurnummer, een bedrag — markeert het niet alleen. Het stelt autonoom een e-mail op en verstuurt deze namens jou naar de juiste partij, met het verzoek om de ontbrekende details. Wanneer het antwoord binnenkomt, werkt FAB je boeken automatisch bij.",
    "about.different.item2.title": "Privacy als Ontwerp",
    "about.different.item2.desc": "FAB wordt lokaal op je apparaat geïnstalleerd. Je financiële gegevens verlaten nooit je computer tenzij je expliciet kiest voor synchronisatie. End-to-end encryptie beschermt alle gegevens tijdens transport, en biometrische login zorgt ervoor dat alleen jij toegang hebt tot je informatie.",
    "about.different.item3.title": "Gebouwd voor het Nederlandse Systeem",
    "about.different.item3.desc": "FAB begrijpt PGB, WLZ, WMO, Wajong en WIA. Het weet hoe geoormerkte zorgfondsen werken, welke betalingen alleen uit specifieke bronnen kunnen komen, en hoe de volledige reis van elke euro door het Nederlandse zorgsysteem te volgen.",
    "about.different.item4.title": "Ontworpen voor Echte Mensen",
    "about.different.item4.desc": "We hebben FAB gebouwd voor mensen die al de eisen van chronische ziekte of beperking beheren. Daarom kost het minder dan 10 minuten per week. De AI doet het zware werk — jij beoordeelt alleen waar het systeem onzeker over is.",
    "about.values.subtitle": "Principes Die",
    "about.values.subtitleHighlight": "Alles Sturen",
    "about.values.subtitleEnd": "Wat We Bouwen",
    "about.values.v1.title": "Empathie Eerst",
    "about.values.v1.desc": "Elke functie die we bouwen begint met de vraag: vermindert dit de last voor iemand die al meer beheert dan de meesten?",
    "about.values.v2.title": "Radicale Transparantie",
    "about.values.v2.desc": "Je gegevens zijn van jou. We geloven in volledige transparantie over hoe je informatie wordt verwerkt, opgeslagen en beschermd.",
    "about.values.v3.title": "Automatisering met Vertrouwen",
    "about.values.v3.desc": "AI moet voor je werken, niet je oordeel vervangen. FAB automatiseert het saaie werk maar geeft jou altijd het laatste woord bij onzekere beslissingen.",
    "about.values.v4.title": "Helderheid Boven Complexiteit",
    "about.values.v4.desc": "We voegen geen functies toe omwille van functies. Elk element in FAB bestaat om je dichter bij het begrijpen van je werkelijke financiële beeld te brengen.",
    "about.impact.biggerPicture": "Het Grotere Plaatje",
    "about.impact.title1": "De",
    "about.impact.titleHighlight": "Werkelijke Kosten",
    "about.impact.titleEnd": "van een Beperking Onthullen",
    "about.impact.p1": "Naast het helpen van individuen heeft FAB een bredere maatschappelijke missie. Vandaag de dag zijn er geen uitgebreide gegevens over wat chronische ziekte en beperking werkelijk kosten vergeleken met gezonde leeftijdsgenoten. De verborgen kosten — gespecialiseerde apparatuur, woningaanpassingen, dieetbehoeften, extra vervoer, verloren verdiencapaciteit — blijven onzichtbaar in publieke beleidsdiscussies.",
    "about.impact.p2": "Met toestemming van onze gebruikers kan FAB geanonimiseerde financiële gegevens aggregeren om het eerste bewijs op bevolkingsschaal te produceren van de beperkingskostenpremie. Deze gegevens kunnen beleidsmakers, belangenorganisaties en zorginstellingen informeren over de werkelijke financiële last die mensen met een beperking elke dag dragen.",
    "about.impact.p3": "We leven in een tijd waarin zelfs mensen met aanzienlijke gezondheidsproblemen gedwongen worden bijverdiensten te onderhouden om onverhaalbare kosten te dekken. FAB helpt niet alleen die realiteit te beheren — het helpt het zichtbaar te maken zodat het op een dag kan veranderen.",
    "about.impact.stat1": "Nederlandse Uitkeringsontvangers",
    "about.impact.stat1Detail": "Meer dan een miljoen mensen in Nederland ontvangen PGB, Wajong of WIA — elk met complexe financiële ecosystemen.",
    "about.impact.stat2": "Jaarlijkse PGB-Uitgaven",
    "about.impact.stat2Detail": "Miljarden euro's stromen jaarlijks door het PGB-systeem, beheerd door mensen die vaak de tools missen om het goed bij te houden.",
    "about.impact.stat3": "Extra Leefkosten",
    "about.impact.stat3Detail": "Onderzoek toont aan dat mensen met een beperking 30% of meer aan extra leefkosten hebben vergeleken met hun niet-gehandicapte leeftijdsgenoten.",
    "about.vision.label": "Onze Visie",
    "about.vision.title1": "Een Wereld Waarin Gezondheidsproblemen",
    "about.vision.titleHighlight": "Niet Bepalen",
    "about.vision.titleEnd": "Financiële Uitkomsten",
    "about.vision.p1": "We stellen ons een toekomst voor waarin niemand hoeft te kiezen tussen het beheren van hun gezondheid en het beheren van hun financiën. Waarin de werkelijke kosten van een beperking zichtbaar, erkend en aangepakt worden. Waarin technologie dient als een brug naar financiële onafhankelijkheid, niet als nog een barrière om te overwinnen.",
    "about.vision.p2": "Beginnend in Nederland zal FAB uitbreiden om mensen met complexe gezondheidsgerelateerde financiën in heel Europa en daarbuiten te bedienen. Want de behoefte aan financiële helderheid is universeel, zelfs als de systemen die de complexiteit creëren lokaal zijn.",

    // FAQ page
    "faq.badge": "Veelgestelde Vragen",
    "faq.title1": "Alles Wat Je Moet",
    "faq.titleHighlight": "Weten",
    "faq.desc": "Vind antwoorden op veelgestelde vragen over FAB, van gegevensprivacy en PGB-integratie tot ons prijsmodel en autonome functies.",
    "faq.search": "Zoek een vraag...",
    "faq.results": "resultaten",
    "faq.noResults": "Geen resultaten gevonden",
    "faq.noResultsDesc": "Probeer andere zoekwoorden of blader door de categorieën hieronder.",
    "faq.clear": "Wissen",
    "faq.cta.title": "Nog Vragen?",
    "faq.cta.desc": "Ons team staat klaar om te helpen. Neem contact op en we reageren binnen 24 uur.",
    "faq.cta.primary": "Stel een Vraag",
    "faq.cta.secondary": "Hoe Het Werkt",
    "faq.categories": "Categorieën",
    "faq.questions": "vragen",
    "faq.result": "resultaat",
    "faq.askDirectly": "Stel Ons Direct een Vraag",
    "faq.sidebarDesc": "Ons team begrijpt de unieke uitdagingen van het beheren van financiën gerelateerd aan een beperking.",
    "faq.contactUs": "Neem Contact Op",
    "faq.cat.general": "Algemeen",
    "faq.cat.general.desc": "Leer de basis over FAB en wat het doet",
    "faq.cat.privacy": "Gegevensprivacy & Beveiliging",
    "faq.cat.privacy.desc": "Hoe we je gevoelige financiële gegevens beschermen",
    "faq.cat.pgb": "PGB-Integratie",
    "faq.cat.pgb.desc": "Hoe FAB werkt met het Nederlandse PGB-systeem",
    "faq.cat.pricing": "Prijzen & Facturering",
    "faq.cat.pricing.desc": "Ons eerlijke, op gebruik gebaseerde prijsmodel begrijpen",
    "faq.cat.autonomous": "Autonome Functies",
    "faq.cat.autonomous.desc": "Hoe FAB's AI namens jou werkt",
    "faq.cat.technical": "Technisch & Installatie",
    "faq.cat.technical.desc": "Aan de slag en technische details",

    // Waitlist
    "waitlist.badge": "Vroege Toegang",
    "waitlist.title": "Wees de Eerste die FAB Ervaart",
    "waitlist.desc": "Schrijf je in voor onze wachtlijst om vroege toegang te krijgen bij lancering. We houden je op de hoogte van onze voortgang.",
    "waitlist.email": "E-mailadres",
    "waitlist.emailPlaceholder": "jij@voorbeeld.nl",
    "waitlist.name": "Volledige naam",
    "waitlist.namePlaceholder": "Je naam",
    "waitlist.situation": "Je situatie",
    "waitlist.situationPlaceholder": "Selecteer je situatie",
    "waitlist.situationPGB": "PGB-houder",
    "waitlist.situationWajong": "Wajong-ontvanger",
    "waitlist.situationWIA": "WIA-ontvanger",
    "waitlist.situationCaregiver": "Mantelzorger / familielid",
    "waitlist.situationOther": "Anders",
    "waitlist.submit": "Inschrijven",
    "waitlist.submitting": "Bezig...",
    "waitlist.success.title": "Je staat op de lijst!",
    "waitlist.success.desc": "Bedankt voor je interesse in FAB. We laten je weten zodra vroege toegang beschikbaar is.",
    "waitlist.success.close": "Sluiten",
    "waitlist.success.alreadyTitle": "Je staat al op de lijst!",
    "waitlist.success.alreadyDesc": "Dit e-mailadres is al geregistreerd. We laten je weten zodra vroege toegang beschikbaar is.",
    "waitlist.privacy": "We respecteren je privacy. Geen spam, ooit.",

    // How It Works page
    "hiwPage.badge": "Hoe FAB Werkt",
    "hiwPage.title1": "Je Reis van",
    "hiwPage.titleHighlight": "Chaos naar Helderheid",
    "hiwPage.desc": "Een gedetailleerde uitleg van hoe FAB verspreide financiële gegevens transformeert naar gestructureerde, bruikbare inzichten — automatisch.",
    "hiwPage.step": "Stap",
    "hiwPage.stepOne": "Stap Eén",
    "hiwPage.step1.title": "Verbind & Beheer Je Platforms",
    "hiwPage.step1.desc": "FAB leest niet alleen je gegevens — het beheert actief je accounts op MijnGeldzaken.nl, WaveApps, SVB en je bank. Via een eenvoudige onboarding-wizard autoriseer je FAB om veilig toegang te krijgen tot en te werken met je accounts via OAuth. FAB wordt je financiële commandocentrum dat acties orkestreert over alle platforms, zodat je nooit meer apart hoeft in te loggen.",
    "hiwPage.step1.gmail": "Facturen, bonnen en financiële bevestigingen uit je inbox.",
    "hiwPage.step1.whatsapp": "Foto's van bonnen, betalingsbevestigingen en berichten van leveranciers.",
    "hiwPage.step1.drive": "Gescande documenten, spreadsheets en financiële administratie.",
    "hiwPage.step1.bank": "Directe transactiefeeds via PSD2 open banking API's.",
    "hiwPage.step1.mgz": "FAB logt in, maakt boekingen aan en houdt je huishoudadministratie automatisch bij.",
    "hiwPage.step1.wave": "FAB beheert je zakelijke boekhouding en zorgkosten-tracking — facturen aanmaken, transacties categoriseren en rekeningen afstemmen.",
    "hiwPage.step1.svb": "FAB handelt PGB-declaraties af, volgt budgetgebruik en beheert betalingsaanvragen voor zorgverleners.",
    "hiwPage.step1.cash": "Handmatige invoer of foto-scanning van contante bonnen via mobiel.",
    "hiwPage.step1.secure": "Veilig Ontworpen",
    "hiwPage.step1.secureDesc": "Alle verbindingen gebruiken OAuth 2.0 of PSD2-conforme API's. Je inloggegevens worden nooit opgeslagen. Gegevens zijn end-to-end versleuteld en lokaal op je apparaat opgeslagen.",
    "hiwPage.stepTwo": "Stap Twee",
    "hiwPage.step2.title": "AI Extraheert & Categoriseert",
    "hiwPage.step2.desc": "Eenmaal verbonden gaat FAB's AI-engine aan het werk. Het scant elke bron, extraheert financiële gegevens met geavanceerde OCR en natuurlijke taalverwerking, en categoriseert elke transactie intelligent.",
    "hiwPage.step2.scan": "Scan",
    "hiwPage.step2.scanTitle": "Documentscannen",
    "hiwPage.step2.scanDesc": "OCR leest bonnen, facturen en afschriften — extraheert bedragen, datums, leveranciers en beschrijvingen.",
    "hiwPage.step2.classify": "Classificeer",
    "hiwPage.step2.classifyTitle": "AI-Classificatie",
    "hiwPage.step2.classifyDesc": "Machine learning categoriseert elke transactie: huishoudelijk, zorg, bijverdienste of geoormerkte PGB-fondsen.",
    "hiwPage.step2.map": "Map",
    "hiwPage.step2.mapTitle": "Bronmapping",
    "hiwPage.step2.mapDesc": "Elke transactie wordt gekoppeld aan de inkomstenbron of uitgavenbestemming op basis van je gedefinieerde regels.",
    "hiwPage.step2.score": "Score",
    "hiwPage.step2.scoreTitle": "Vertrouwensscore",
    "hiwPage.step2.scoreDesc": "Elke classificatie krijgt een vertrouwensscore. Items met hoge betrouwbaarheid gaan automatisch door; onzekere worden gemarkeerd.",
    "hiwPage.step2.extractTitle": "Wat de AI Extraheert uit Elk Document",
    "hiwPage.step2.vendorName": "Leveranciersnaam",
    "hiwPage.step2.vendorEx": "Albert Heijn, Apotheek, etc.",
    "hiwPage.step2.amount": "Bedrag",
    "hiwPage.step2.amountEx": "€47,50, €125,00, etc.",
    "hiwPage.step2.date": "Datum",
    "hiwPage.step2.dateEx": "01-03-2026, etc.",
    "hiwPage.step2.category": "Categorie",
    "hiwPage.step2.categoryEx": "Zorg, Huishoudelijk, etc.",
    "hiwPage.step2.invoice": "Factuurnummer",
    "hiwPage.step2.invoiceEx": "INV-2026-0042",
    "hiwPage.step2.payment": "Betaalmethode",
    "hiwPage.step2.paymentEx": "iDEAL, Contant, Pinpas",
    "hiwPage.step2.taxDeduct": "Fiscaal Aftrekbaar",
    "hiwPage.step2.taxDeductEx": "Ja / Nee",
    "hiwPage.step2.earmarked": "Geoormerkt Fonds",
    "hiwPage.step2.earmarkedEx": "PGB, WLZ, WMO",
    "hiwPage.stepThree": "Stap Drie",
    "hiwPage.step3.title": "Auto-Routeren, Beheren & Synchroniseren",
    "hiwPage.step3.desc": "Dit is waar FAB echt schittert. Verwerkte transacties worden automatisch gerouteerd naar het juiste platform — en FAB logt in op elk platform om boekingen aan te maken, records bij te werken en alles gesynchroniseerd te houden. Ontbrekende gegevens? FAB e-mailt leveranciers namens jou om de gaten op te vullen.",
    "hiwPage.step3.routing": "Intelligente Routering",
    "hiwPage.step3.r1from": "Huishoudelijke uitgaven",
    "hiwPage.step3.r1to": "mijngeldzaken.nl",
    "hiwPage.step3.r2from": "Bijverdienste inkomsten/uitgaven",
    "hiwPage.step3.r2to": "WaveApps (Zakelijk)",
    "hiwPage.step3.r3from": "Zorggerelateerde kosten",
    "hiwPage.step3.r3to": "WaveApps (Persoonlijk)",
    "hiwPage.step3.r4from": "PGB-zorgverlenerbetalingen",
    "hiwPage.step3.r4to": "SVB",
    "hiwPage.step3.routingNote": "Elk platform is een 'eindstation' — geld en gegevens stromen erin maar niet ertussen. FAB volgt de complete reis van elke euro om dubbeltelling te voorkomen.",
    "hiwPage.step3.autoComplete": "Autonome Gegevensaanvulling",
    "hiwPage.step3.ac1": "Gatendetectie",
    "hiwPage.step3.ac1Desc": "FAB scant de boeken en identificeert vermeldingen met ontbrekende leveranciersnaam, bedrag, datum of factuurnummer.",
    "hiwPage.step3.ac2": "Contactidentificatie",
    "hiwPage.step3.ac2Desc": "Met bestaande gegevensaanwijzingen bepaalt FAB welke partij te contacteren voor de ontbrekende informatie.",
    "hiwPage.step3.ac3": "E-mail Opstellen",
    "hiwPage.step3.ac3Desc": "Een professionele e-mail wordt opgesteld met een standaardsjabloon, waarin de specifieke ontbrekende details worden opgevraagd.",
    "hiwPage.step3.ac4": "Gebruikersgoedkeuring",
    "hiwPage.step3.ac4Desc": "Je beoordeelt en keurt de e-mail goed voordat deze vanuit je inbox wordt verzonden. Volledige controle, altijd.",
    "hiwPage.step3.ac5": "Antwoordverwerking",
    "hiwPage.step3.ac5Desc": "Wanneer de leverancier antwoordt, parseert FAB het antwoord en werkt de boeking automatisch bij.",
    "hiwPage.step3.ac6": "Opvolging",
    "hiwPage.step3.ac6Desc": "Als er geen antwoord komt binnen je ingestelde termijn, stuurt FAB een herinnering (tot je geconfigureerde maximum aantal pogingen).",
    "hiwPage.step3.sync": "Continue Synchronisatie",
    "hiwPage.step3.syncDesc": "FAB synchroniseert continu met al je platforms om alles up-to-date te houden. Je bepaalt de frequentie met eenvoudige schuifregelaars voor elk bewerkingstype.",
    "hiwPage.step3.syncPlatform": "Platformsynchronisatie",
    "hiwPage.step3.syncPlatformFreq": "Elk uur",
    "hiwPage.step3.syncPlatformDesc": "Nieuwe gegevens ophalen van mijngeldzaken.nl, WaveApps, SVB en bankrekeningen.",
    "hiwPage.step3.syncSource": "Bronscannen",
    "hiwPage.step3.syncSourceFreq": "Elk uur",
    "hiwPage.step3.syncSourceDesc": "Gmail, WhatsApp en Google Drive controleren op nieuwe financiële documenten.",
    "hiwPage.step3.syncData": "Gegevensaanvulling",
    "hiwPage.step3.syncDataFreq": "Elke 5 minuten",
    "hiwPage.step3.syncDataDesc": "Controleren op e-mailantwoorden van leveranciers en onvolledige vermeldingen automatisch bijwerken.",
    "hiwPage.step3.adjustable": "Aanpasbaar via instellingen",
    "hiwPage.stepFour": "Stap Vier",
    "hiwPage.step4.title": "Beoordelen & Ontspannen",
    "hiwPage.step4.desc": "Elke week besteed je minder dan 10 minuten aan het beoordelen van alleen wat de AI onzeker over is. Al het andere is automatisch afgehandeld. Zo ziet je wekelijkse beoordeling eruit:",
    "hiwPage.step4.queue": "Je Wekelijkse Beoordelingswachtrij",
    "hiwPage.step4.queueNote": "Slechts 3 items deze week hebben je aandacht nodig. De andere 47 transacties zijn automatisch verwerkt.",
    "hiwPage.step4.unknownVendor": "Onbekende Leverancier",
    "hiwPage.step4.vendorName": "Leveranciersnaam",
    "hiwPage.step4.healthcare": "Zorg?",
    "hiwPage.step4.categoryLabel": "Categorie",
    "hiwPage.step4.healthHousehold": "Zorg / Huishoudelijk?",
    "hiwPage.step4.householdSide": "Huishoudelijk / Bijverdienste?",
    "hiwPage.step4.summary": "Samenvatting Deze Week",
    "hiwPage.step4.autoProcessed": "transacties automatisch verwerkt",
    "hiwPage.step4.needReview": "items hebben je beoordeling nodig",
    "hiwPage.step4.totalProcessed": "totaal verwerkt deze week",
    "hiwPage.step4.healthCosts": "zorgkosten geïdentificeerd",
    "hiwPage.step4.timeSaved": "Tijd Bespaard",
    "hiwPage.step4.hoursWeek": "uur deze week",
    "hiwPage.step4.compared": "Vergeleken met handmatige boekhouding",
    "hiwPage.flow.label": "Het Complete Beeld",
    "hiwPage.flow.title": "End-to-End Gegevensstroom",
    "hiwPage.flow.desc": "Van verspreide documenten naar gestructureerde helderheid — hier is de complete reis van je financiële gegevens door FAB.",
    "hiwPage.flow.sources": "Gegevensbronnen",
    "hiwPage.flow.engine": "FAB Verwerkingsengine",
    "hiwPage.flow.endStations": "Eindstation-Platforms",
    "hiwPage.flow.household": "Huishoudelijk",
    "hiwPage.flow.sideHustle": "Bijverdienste",
    "hiwPage.flow.healthcareType": "Zorg",
    "hiwPage.flow.pgbPayments": "PGB-Betalingen",
    "hiwPage.flow.result": "Resultaat",
    "hiwPage.flow.resultTitle": "Volledige Financiële Helderheid",
    "hiwPage.flow.resultDesc": "Uniform overzicht over alle platforms met kwantificering van zorgkosten",
    "hiwPage.flow.ocrExtraction": "OCR-Extractie",
    "hiwPage.flow.aiClassification": "AI-Classificatie",
    "hiwPage.flow.sourceMapping": "Bronmapping",
    "hiwPage.flow.confidenceScoring": "Vertrouwensscore",
    "hiwPage.flow.gapDetection": "Gatendetectie",
    "hiwPage.flow.autoEmail": "Auto-E-mail",

    // Footer legal items
    "footer.legal.privacypolicy": "Privacybeleid",
    "footer.legal.termsofservice": "Algemene Voorwaarden",
    "footer.legal.gdpr": "AVG",
    "footer.legal.cookiepolicy": "Cookiebeleid",

    // Payment pages
    "payment.verifying": "Betaling verifiëren...",
    "payment.success.title": "Gebruiksfacturatie gereed",
    "payment.success.desc": "Je betaalmethode is gereed voor gecontroleerde gebruiksfacturen. FAB rekent resourcekosten x 2,5 en geen vast maandbedrag.",
    "payment.success.emailNote": "Factuurcontact",
    "payment.success.cta": "Ga naar Dashboard",
    "payment.error.title": "Er Ging Iets Mis",
    "payment.error.desc": "We konden je betaling niet verifiëren. Als je denkt dat dit een fout is, neem dan contact op met ons supportteam.",
    "payment.error.cta": "Contact Support",
    "payment.cancel.title": "Betaling Geannuleerd",
    "payment.cancel.desc": "Geen zorgen — je kunt altijd terugkomen en je abonneren wanneer je er klaar voor bent. Je gegevens zijn veilig bij ons.",
    "payment.cancel.cta": "Terug naar Home",

    // Account page
    "account.title": "Mijn Account",
    "account.welcome": "Welkom terug",
    "account.user": "Gebruiker",
    "account.subtitle": "Beheer je abonnement, facturering en accountinstellingen.",
    "account.loginRequired": "Inloggen Vereist",
    "account.loginRequiredDesc": "Log in om je accountinstellingen en abonnementsgegevens te bekijken.",
    "account.profile": "Profiel",
    "account.logout": "Uitloggen",
    "account.name": "Naam",
    "account.email": "E-mail",
    "account.memberSince": "Lid Sinds",
    "account.plan": "Huidig Abonnement",
    "account.freePlan": "Gratis Abonnement",
    "account.subscription": "Gebruiksfacturatie",
    "account.statusActive": "Actief",
    "account.statusTrialing": "Proefperiode",
    "account.statusPastDue": "Achterstallig",
    "account.statusCanceled": "Geannuleerd",
    "account.statusFree": "Gratis",
    "account.currentPeriodEnd": "Huidige Periode Eindigt",
    "account.autoRenew": "Automatische Verlenging",
    "account.cancelAtEnd": "Wordt geannuleerd aan het einde van de periode",
    "account.autoRenewYes": "Ingeschakeld",
    "account.manageBilling": "Facturering Beheren",
    "account.portalRedirect": "Factureringsportaal openen...",
    "account.checkoutRedirect": "Doorsturen naar afrekenen...",
    "account.freePlanTitle": "Je hebt het Gratis Abonnement",
    "account.freePlanDesc": "Upgrade naar Betaal per Gebruik voor onbeperkte documentverwerking, meerdere bankverbindingen en prioriteitsondersteuning.",
    "account.upgradeCta": "Upgrade naar Betaal per Gebruik",
    "account.invoices": "Factuurgeschiedenis",
    "account.noInvoices": "Nog geen facturen. Je facturen verschijnen hier zodra je een abonnement neemt.",
    "account.invoiceDate": "Datum",
    "account.invoiceAmount": "Bedrag",
    "account.invoiceStatus": "Status",
    "account.invoiceActions": "Acties",
    "account.viewInvoice": "Factuur Bekijken",
    "account.downloadPdf": "PDF Downloaden",
    "nav.account": "Account",

    // Legal layout
    "legal.backHome": "Terug naar Home",
    "legal.lastUpdated": "Laatst bijgewerkt",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("fab-lang");
      if (saved === "en" || saved === "nl") return saved;
    }
    return "en";
  });

  const setLang = useCallback((newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("fab-lang", newLang);
  }, []);

  const t = useCallback(
    (key: string) => translations[lang][key] || translations.en[key] || key,
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
