import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

type Language = "en" | "nl";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.howItWorks": "How It Works",
    "nav.features": "Features",
    "nav.security": "Security",
    "nav.pricing": "Pricing",
    "nav.impact": "Impact",
    "nav.about": "About",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "nav.blog": "Blog",
    "nav.home": "Home",
    "nav.signIn": "Sign In",
    "nav.getStarted": "Get Started",

    // Hero
    "hero.badge": "Financial Clarity for Everyone",
    "hero.title1": "Bring Structure &",
    "hero.titleHighlight": "Clarity",
    "hero.title2": "to Your Finances",
    "hero.desc": "FAB is a local financial operations platform for document intake, assisted bookkeeping, review, reconciliation, reporting, and governed provider handoffs.",
    "hero.cta1": "Get Started Free",
    "hero.cta2": "See How It Works",
    "hero.stat1": "<10 min/week",
    "hero.stat2": "E2E Encrypted",
    "hero.stat3": "Desktop & Mobile",

    // Problem
    "problem.label": "The Challenge",
    "problem.title": "Managing Finances Shouldn't Be a Full-Time Job",
    "problem.desc": "For individuals managing disability or chronic illness, financial administration is scattered across WhatsApp messages, email inboxes, Google Drive folders, and multiple platforms. This chaos consumes hours every week — time better spent on health and well-being.",
    "problem.card1.title": "Scattered Documents",
    "problem.card1.desc": "Receipts in WhatsApp, invoices in Gmail, statements in Drive. No single source of truth for your finances.",
    "problem.card1.stat": "5+",
    "problem.card1.statLabel": "data sources",
    "problem.card2.title": "Hours of Manual Work",
    "problem.card2.desc": "Manually entering transactions, chasing vendors for missing information, reconciling across platforms.",
    "problem.card2.stat": "4-8",
    "problem.card2.statLabel": "hours per week",
    "problem.card3.title": "Hidden Health Costs",
    "problem.card3.desc": "The true financial impact of disability remains invisible — spread across earmarked funds, insurance, and out-of-pocket expenses.",
    "problem.card3.stat": "€17K+",
    "problem.card3.statLabel": "extra annual costs",

    // How It Works
    "hiw.label": "How It Works",
    "hiw.title": "From Chaos to Clarity in Four Steps",
    "hiw.desc": "FAB works quietly in the background, transforming scattered financial data into structured, actionable clarity.",
    "hiw.step1.title": "Connect & Manage Your Platforms",
    "hiw.step1.desc": "Connect only the sources you choose. Each connector reports whether it is live, supervised, or not yet available.",
    "hiw.step2.title": "AI Extracts & Categorizes",
    "hiw.step2.desc": "FAB scans supported documents, extracts financial data with OCR, and proposes categories with confidence and provenance.",
    "hiw.step3.title": "Auto-Route & Manage",
    "hiw.step3.desc": "FAB prepares governed routing and export work. External changes require a supported connector, evidence, and the configured approval gate.",
    "hiw.step4.title": "Review & Control",
    "hiw.step4.desc": "Review uncertainty, duplicates, mappings, and external drafts from one queue. FAB never hides work that still needs a decision.",

    // Features
    "features.orch.label": "Intelligent Orchestration",
    "features.orch.title": "One Platform, All Your Financial Tools",
    "features.orch.desc": "FAB keeps local intake, review, routing, reconciliation, reporting, and provider handoffs in one auditable workflow.",
    "features.orch.item1": "Capability-aware connector states",
    "features.orch.item2": "Category and fund routing rules",
    "features.orch.item3": "Configurable local processing cycles",
    "features.orch.item4": "Conflict detection and review queues",
    "features.ai.label": "AI-Powered Processing",
    "features.ai.title": "Evidence-Aware Bookkeeping Assistance",
    "features.ai.desc": "FAB extracts and categorizes documents, records confidence and provenance, and routes uncertain or incomplete work to review.",
    "features.ai.item1": "OCR scanning of receipts and invoices",
    "features.ai.item2": "Review-gated vendor follow-up drafts",
    "features.ai.item3": "Confidence-based flagging system",
    "features.ai.item4": "Continuous learning from corrections",
    "features.dash.label": "Unified Dashboard",
    "features.dash.title": "See Your Complete Financial Picture",
    "features.dash.desc": "See source evidence, bookkeeping records, review decisions, reconciliation, compliance findings, and provider delivery state in one operational view.",
    "features.dash.item1": "Current ledger and workflow status",
    "features.dash.item2": "Healthcare cost quantification reports",
    "features.dash.item3": "Reviewable tax and compliance summaries",
    "features.dash.item4": "Export in universal formats (CSV, PDF)",

    // Integrations
    "integrations.label": "Connected Platforms",
    "integrations.title": "One Control Layer for Existing Tools",
    "integrations.desc": "FAB is a local source of truth that separates live APIs, supervised handoffs, imports, and roadmap capabilities instead of presenting them as equivalent.",
    "integrations.mgz.title": "MijnGeldzaken.nl",
    "integrations.mgz.desc": "FAB prepares a reviewable master-ledger export for supervised MijnGeldzaken handling. Direct account mutation is not presented as live.",
    "integrations.mgz.tag": "Household Finance",
    "integrations.wave.title": "Wave Apps",
    "integrations.wave.desc": "FAB mirrors supported Wave data and prepares approval-gated operations. Receipt delivery is complete only after downstream attachment readback is verified.",
    "integrations.wave.tag": "Accounting",
    "integrations.banks.title": "Dutch Banks",
    "integrations.banks.desc": "FAB imports supported bank statement files and reconciles transactions locally. Direct PSD2 feeds remain capability-gated until a provider is configured.",
    "integrations.banks.tag": "Banking",
    "integrations.svb.title": "SVB (Sociale Verzekeringsbank)",
    "integrations.svb.desc": "PGB and SVB records can be categorized and reported locally. Direct declarations and payment submissions are not currently executed by FAB.",
    "integrations.svb.tag": "PGB Management",
    "integrations.google.title": "Gmail & Google Drive",
    "integrations.google.desc": "With owner consent, FAB reads configured Gmail and Drive sources, deduplicates evidence, and imports supported documents into the reviewable local workflow.",
    "integrations.google.tag": "Document Sources",
    "integrations.more.title": "More Integrations Coming",
    "integrations.more.desc": "We're continuously expanding our platform connections. WhatsApp Business, Exact Online, Moneybird, and more are on our roadmap.",
    "integrations.more.tag": "Roadmap",
    "integrations.callout.title": "Capabilities are explicit",
    "integrations.callout.desc": "Every connector exposes its readiness, supported actions, review requirements, and evidence state. Unsupported external mutations remain blocked rather than simulated.",
    "integrations.cta": "See How It Works",

    // Stats
    "stats.users": "Source of Truth",
    "stats.usersSub": "Local operational ledger",
    "stats.budget": "Retention Policy",
    "stats.budgetSub": "Configurable Dutch evidence horizon",
    "stats.minutes": "External Changes",
    "stats.minutesSub": "Approval and capability gated",
    "stats.saved": "Evidence Integrity",
    "stats.savedSub": "Source and attachment checksums",

    // Testimonials
    "testimonials.label": "Operating Principles",
    "testimonials.title": "Automation You Can Inspect",
    "testimonials.desc": "FAB's behavior is defined by evidence, explicit authority, and recoverable state rather than unverified outcome claims.",
    "testimonials.t1.quote": "External bookkeeping changes require a supported provider capability and the configured approval path.",
    "testimonials.t1.name": "Approval Gate",
    "testimonials.t1.role": "External operations",
    "testimonials.t2.quote": "Every imported document retains source provenance and a checksum before it can move through bookkeeping.",
    "testimonials.t2.name": "Evidence Chain",
    "testimonials.t2.role": "Documents and attachments",
    "testimonials.t3.quote": "Low-confidence extraction, ambiguous categorization, duplicates, and discrepancies remain visible for review.",
    "testimonials.t3.name": "Human Review",
    "testimonials.t3.role": "Uncertain decisions",
    "testimonials.t4.quote": "A persistent emergency stop blocks new autonomous steps and only an operator can resume processing.",
    "testimonials.t4.name": "Fail-Closed Control",
    "testimonials.t4.role": "Autonomous workflows",
    "testimonials.trustBadge1": "Privacy First",
    "testimonials.trustBadge2": "GDPR Compliant",
    "testimonials.trustBadge3": "Dutch-Built",
    "testimonials.trustBadge4": "Open Source Core",

    // Blog / Updates
    "blog.label": "Latest Updates",
    "blog.title": "News & Insights",
    "blog.desc": "Stay up to date with FAB's development journey, product milestones, and insights on financial accessibility.",
    "blog.readMore": "Read More",
    "blog.viewAll": "View All Updates",
    "blog.backToBlog": "Back to Blog",
    "blog.publishedOn": "Published on",
    "blog.minRead": "min read",
    "blog.noPosts": "No posts yet. Check back soon!",
    "blog.pageTitle": "Blog & Updates",
    "blog.pageDesc": "Product milestones, feature previews, and insights on making financial management accessible for everyone.",
    "blog.badge": "Blog & Updates",
    "blog.searchPlaceholder": "Search articles...",
    "blog.allPosts": "All Posts",
    "blog.catUpdate": "Update",
    "blog.catMilestone": "Milestone",
    "blog.catFeature": "Feature",
    "blog.catAnnouncement": "Announcement",
    "blog.catTechnology": "Technology",
    "blog.catGuide": "Guide",
    "blog.noPostsDesc": "We're working on new content. Check back soon for updates on FAB's development.",
    "blog.readTime": "read",
    "blog.postNotFound": "Post Not Found",
    "blog.postNotFoundDesc": "The blog post you're looking for doesn't exist or has been removed.",
    "blog.ctaTitle": "Enjoyed this article?",
    "blog.ctaDesc": "Explore more updates and insights about FAB's journey.",
    "blog.ctaButton": "Browse All Posts",

    // Security
    "security.label": "Privacy & Security",
    "security.title": "Your Data Stays Yours",
    "security.desc": "FAB keeps the operational ledger local by default, protects stored connector secrets, uses authenticated transport where configured, and records compliance evidence for review.",
    "security.e2e": "Protected Secrets",
    "security.e2eDesc": "Connector secrets are encrypted locally and never returned by readiness APIs",
    "security.gdpr": "Compliance Evidence",
    "security.gdprDesc": "Retention and privacy findings remain reviewable, not self-certified",
    "security.bio": "Access Control",
    "security.bioDesc": "Loopback safeguards, local authentication, and bounded operator authority",
    "security.export": "Data Export",
    "security.exportDesc": "Export or delete all your data anytime",
    "security.local": "Local ledger with explicit provider handoffs",
    "security.2fa": "Provider MFA remains provider-controlled",
    "security.emailApproval": "Approval before external communication",
    "security.offline": "Core local review works without provider access",
    "security.gdprExport": "Auditable retention and export controls",
    "security.trusted": "Operator-only approval and emergency-stop controls",

    // Pricing
    "pricing.label": "Pricing",
    "pricing.title": "Pay Only for What You Use",
    "pricing.desc": "FAB uses a transparent, resource-based pricing model. You only pay for the resources you consume — no hidden fees, no surprises.",
    "pricing.free.label": "Free Tier",
    "pricing.free.price": "€0",
    "pricing.free.period": "/forever",
    "pricing.free.desc": "Get started and experience FAB's core value.",
    "pricing.free.item1": "3 transactions per week",
    "pricing.free.item2": "All platform integrations",
    "pricing.free.item3": "AI categorization",
    "pricing.free.item4": "Basic reporting",
    "pricing.free.item5": "Desktop & mobile access",
    "pricing.free.cta": "Start Free",
    "pricing.payg.label": "Pay As You Go",
    "pricing.payg.formula": "Usage × 2.5",
    "pricing.payg.desc": "Fair, transparent pricing based on actual resource usage.",
    "pricing.payg.item1": "Unlimited transactions",
    "pricing.payg.item2": "Autonomous data completion",
    "pricing.payg.item3": "Full email automation",
    "pricing.payg.item4": "Advanced reporting & tax summaries",
    "pricing.payg.item5": "Real-time cost dashboard",
    "pricing.payg.item6": "Configurable spending cap",
    "pricing.payg.item7": "Priority support",
    "pricing.payg.cta": "Get Started",

    // Impact
    "impact.label": "Social Impact",
    "impact.title": "Measuring the True Cost of Disability",
    "impact.desc": "FAB is more than a financial tool. By aggregating anonymized data, we can publish first-of-its-kind reports on the true financial burden of living with a disability — providing evidence for better policy and support.",
    "impact.card1.title": "Financial Empowerment",
    "impact.card1.desc": "Give back time and energy to individuals who need it most.",
    "impact.card2.title": "Cost Transparency",
    "impact.card2.desc": "Quantify the true 'disability cost premium' at population scale.",
    "impact.card3.title": "Policy Evidence",
    "impact.card3.desc": "Anonymized data to inform better disability policy and support.",
    "impact.card4.title": "Community Strength",
    "impact.card4.desc": "Build a network of empowered individuals who understand their financial reality.",

    // CTA
    "cta.title": "Ready to Bring Clarity to Your Finances?",
    "cta.desc": "Join the movement towards financial empowerment. Start with 3 free transactions per week and experience the difference.",
    "cta.primary": "Get Started Free",
    "cta.secondary": "Contact Us",

    // Footer
    "footer.desc": "Financial Structure & Clarity for individuals managing complex health-related finances in the Netherlands.",
    "footer.product": "Product",
    "footer.company": "Company",
    "footer.legal": "Legal",
    "footer.rights": "All rights reserved.",
    "footer.madeWith": "Made with",
    "footer.inNL": "in the Netherlands",

    // Contact page
    "contact.badge": "Get in Touch",
    "contact.title1": "Let's Start a",
    "contact.titleHighlight": "Conversation",
    "contact.desc": "Have questions about FAB? Want to learn how we can bring clarity to your finances? We'd love to hear from you.",
    "contact.form.firstName": "First Name",
    "contact.form.lastName": "Last Name",
    "contact.form.email": "Email Address",
    "contact.form.topic": "Topic",
    "contact.form.topicPlaceholder": "Select a topic",
    "contact.form.message": "Message",
    "contact.form.messagePlaceholder": "Tell us how we can help you...",
    "contact.form.send": "Send Message",
    "contact.form.sending": "Sending...",
    "contact.success.title": "Message Sent!",
    "contact.success.desc": "Thank you for reaching out. We'll get back to you within 24 hours.",
    "contact.success.another": "Send Another Message",
    "contact.success.backHome": "Back to Home",
    "contact.success.toast": "Message sent successfully!",
    "contact.info.email": "Email Us",
    "contact.info.response": "Response Time",
    "contact.info.responseVal": "Within 24 hours",
    "contact.info.location": "Location",
    "contact.info.locationVal": "The Netherlands",
    "contact.info.phone": "Phone",
    "contact.info.phoneVal": "Schedule a call",
    "contact.info.faq": "Check our FAQ",
    "contact.info.faqDesc": "Check our frequently asked questions for instant answers to common inquiries about FAB's features, pricing, and security.",
    "contact.info.faqLink": "Visit FAQ",
    "contact.topic.select": "Select a topic...",
    "contact.topic.general": "General Inquiry",
    "contact.topic.demo": "Request a Demo",
    "contact.topic.pricing": "Pricing & Plans",
    "contact.topic.partnership": "Partnership Opportunities",
    "contact.topic.support": "Technical Support",
    "contact.topic.accessibility": "Accessibility Question",
    "contact.topic.media": "Media & Press",
    "contact.error.firstName": "First name is required",
    "contact.error.lastName": "Last name is required",
    "contact.error.email": "Email is required",
    "contact.error.emailInvalid": "Please enter a valid email address",
    "contact.error.subject": "Please select a topic",
    "contact.error.message": "Message is required",
    "contact.error.messageLength": "Message must be at least 10 characters",
    "contact.form.firstNamePlaceholder": "Your first name",
    "contact.form.lastNamePlaceholder": "Your last name",
    "contact.form.emailPlaceholder": "you@example.com",
    "contact.form.messagePlaceholderLong": "Tell us how we can help...",

    // FAQut page
    "about.badge": "Our Story",
    "about.title1": "Born from",
    "about.titleHighlight": "Lived Experience",
    "about.title2": "Built for Real People",
    "about.mission.label": "Our Mission",
    "about.mission.title": "Financial Clarity in Less Than 10 Minutes a Week",
    "about.different.label": "What Makes Us Different",
    "about.values.label": "Our Values",
    "about.impact.label": "Our Impact Vision",
    "about.cta.title": "Join Us in Building Financial Clarity",
    "about.cta.desc": "Whether you're a PGB holder, a Wajong recipient, or managing finances with a chronic condition — FAB is built for you.",
    "about.cta.primary": "Get Started Free",
    "about.cta.secondary": "Contact Us",
    "about.hero.desc": "FAB was not created in a boardroom. It was born from the daily reality of managing a household while navigating the financial complexity that comes with chronic illness and disability. We understand the struggle because we have lived it.",
    "about.problem.title1": "The Problem",
    "about.problem.titleHighlight": "We Lived",
    "about.problem.p1": "Living with a chronic illness or disability in the Netherlands means navigating a labyrinth of financial obligations. Your household expenses are tracked in one place, your PGB (Persoonsgebonden Budget) payments flow through SVB, your side-hustle income lives in WaveApps, and critical receipts are scattered across WhatsApp messages, Gmail inboxes, and Google Drive folders.",
    "about.problem.p2": "The result is financial chaos. Hours spent every week manually entering data, chasing missing receipts, and trying to reconcile accounts across platforms that were never designed to talk to each other. Hours that people managing health conditions simply do not have.",
    "about.problem.p3pre": "Worse still, this fragmentation makes it impossible to answer a fundamental question:",
    "about.problem.p3quote": "What does my illness or disability actually cost me?",
    "about.problem.p3post": "Without that answer, there is no clarity, no control, and no path to financial stability.",
    "about.mission.subtitle": "Financial Structure and Clarity,",
    "about.mission.subtitleHighlight": "Without the Burden",
    "about.mission.desc": "Our mission is to reduce repetitive administration while keeping financial decisions, uncertain evidence, and external changes visible to the person responsible.",
    "about.mission.pillar1.title": "Automate the Chaos",
    "about.mission.pillar1.desc": "FAB extracts supported documents from configured local, Gmail, Drive, and photo sources, then validates and routes uncertain results to review.",
    "about.mission.pillar2.title": "Orchestrate Your Ecosystem",
    "about.mission.pillar2.desc": "We do not replace existing tools. FAB records what each connector can read, prepare, submit, and verify, with a local master ledger as the auditable center.",
    "about.mission.pillar3.title": "Reveal the True Cost",
    "about.mission.pillar3.desc": "Reviewed categories and reports can help you examine health-related costs without presenting provisional classifications as settled facts.",
    "about.different.subtitle": "Not Just Another",
    "about.different.subtitleHighlight": "Finance App",
    "about.different.desc": "Most financial tools ask you to do the work. FAB does the work for you. Here is what sets us apart.",
    "about.different.item1.title": "Self-Completing Books",
    "about.different.item1.desc": "When FAB finds missing information, it records the gap and can prepare a follow-up draft. Sending and applying a response remain approval and evidence gated.",
    "about.different.item2.title": "Privacy by Design",
    "about.different.item2.desc": "FAB runs locally and makes provider handoffs explicit. Connector secrets are encrypted locally, sensitive values are redacted from diagnostics, and remote API exposure is blocked without authentication.",
    "about.different.item3.title": "Built for the Dutch System",
    "about.different.item3.desc": "FAB provides Dutch bookkeeping, VAT, retention, and health-cost classification support, while statutory conclusions remain provisional until reviewed.",
    "about.different.item4.title": "Designed for Real People",
    "about.different.item4.desc": "FAB prioritizes the review queue, explains blockers, and automates eligible local work so the operator can focus on decisions that actually require judgment.",
    "about.values.subtitle": "Principles That",
    "about.values.subtitleHighlight": "Guide Everything",
    "about.values.subtitleEnd": "We Build",
    "about.values.v1.title": "Empathy First",
    "about.values.v1.desc": "Every feature we build starts with the question: does this reduce the burden on someone who is already managing more than most?",
    "about.values.v2.title": "Radical Transparency",
    "about.values.v2.desc": "Your data is yours. We believe in complete transparency about how your information is processed, stored, and protected.",
    "about.values.v3.title": "Automation with Trust",
    "about.values.v3.desc": "AI should work for you, not replace your judgment. FAB automates the tedious work but always gives you the final say on uncertain decisions.",
    "about.values.v4.title": "Clarity Over Complexity",
    "about.values.v4.desc": "We do not add features for the sake of features. Every element in FAB exists to bring you closer to understanding your true financial picture.",
    "about.impact.biggerPicture": "The Bigger Picture",
    "about.impact.title1": "Revealing the",
    "about.impact.titleHighlight": "True Cost",
    "about.impact.titleEnd": "of Disability",
    "about.impact.p1": "Beyond helping individuals, FAB has a broader social mission. Today, there is no comprehensive data on what chronic illness and disability truly cost a person compared to their healthy peers. The hidden expenses — specialized equipment, home modifications, dietary needs, additional transportation, lost earning potential — remain invisible in public policy discussions.",
    "about.impact.p2": "With the consent of our users, FAB can aggregate anonymized financial data to produce the first population-scale evidence of the disability cost premium. This data can inform policy makers, advocacy organizations, and healthcare institutions about the real financial burden that individuals with disabilities carry every day.",
    "about.impact.p3": "We live in a time where even individuals with significant health challenges are forced to maintain side-hustles to cover unrecoupable costs. FAB not only helps manage that reality — it helps make it visible so that, one day, it can change.",
    "about.impact.stat1": "Dutch Disability Benefit Recipients",
    "about.impact.stat1Detail": "Over one million people in the Netherlands receive PGB, Wajong, or WIA benefits — each managing complex financial ecosystems.",
    "about.impact.stat2": "Annual PGB Expenditure",
    "about.impact.stat2Detail": "Billions of euros flow through the PGB system annually, managed by individuals who often lack the tools to track it properly.",
    "about.impact.stat3": "Extra Living Costs",
    "about.impact.stat3Detail": "Research shows people with disabilities face 30% or more in additional living costs compared to their non-disabled peers.",
    "about.vision.label": "Our Vision",
    "about.vision.title1": "A World Where Health Conditions",
    "about.vision.titleHighlight": "Do Not Define",
    "about.vision.titleEnd": "Financial Outcomes",
    "about.vision.p1": "We envision a future where no one has to choose between managing their health and managing their finances. Where the true cost of disability is visible, acknowledged, and addressed. Where technology serves as a bridge to financial independence, not another barrier to overcome.",
    "about.vision.p2": "Starting in the Netherlands, FAB will expand to serve individuals with complex health-related finances across Europe and beyond. Because the need for financial clarity is universal, even if the systems that create the complexity are local.",

    // FAQ page
    "faq.badge": "Frequently Asked Questions",
    "faq.title1": "Everything You Need",
    "faq.titleHighlight": "to Know",
    "faq.desc": "Find answers to common questions about FAB, from data privacy and PGB integration to our pricing model and autonomous features.",
    "faq.search": "Search for a question...",
    "faq.results": "results",
    "faq.noResults": "No results found",
    "faq.noResultsDesc": "Try different keywords or browse the categories below.",
    "faq.clear": "Clear",
    "faq.cta.title": "Still Have Questions?",
    "faq.cta.desc": "Our team is here to help. Reach out and we'll get back to you within 24 hours.",
    "faq.cta.primary": "Ask a Question",
    "faq.cta.secondary": "How It Works",
    "faq.categories": "Categories",
    "faq.questions": "questions",
    "faq.result": "result",
    "faq.askDirectly": "Ask Us Directly",
    "faq.sidebarDesc": "Our team understands the unique challenges of managing disability-related finances.",
    "faq.contactUs": "Contact Us",
    "faq.cat.general": "General",
    "faq.cat.general.desc": "Learn the basics about FAB and what it does",
    "faq.cat.privacy": "Data Privacy & Security",
    "faq.cat.privacy.desc": "How we protect your sensitive financial data",
    "faq.cat.pgb": "PGB Integration",
    "faq.cat.pgb.desc": "How FAB works with the Dutch PGB system",
    "faq.cat.pricing": "Pricing & Billing",
    "faq.cat.pricing.desc": "Understanding our fair, usage-based pricing",
    "faq.cat.autonomous": "Autonomous Features",
    "faq.cat.autonomous.desc": "How FAB's AI works on your behalf",
    "faq.cat.technical": "Technical & Setup",
    "faq.cat.technical.desc": "Getting started and technical details",

    // Waitlist
    "waitlist.badge": "Early Access",
    "waitlist.title": "Be the First to Experience FAB",
    "waitlist.desc": "Join our waitlist to get early access when we launch. We'll keep you updated on our progress.",
    "waitlist.email": "Email address",
    "waitlist.emailPlaceholder": "you@example.com",
    "waitlist.name": "Full name",
    "waitlist.namePlaceholder": "Your name",
    "waitlist.situation": "Your situation",
    "waitlist.situationPlaceholder": "Select your situation",
    "waitlist.situationPGB": "PGB holder",
    "waitlist.situationWajong": "Wajong recipient",
    "waitlist.situationWIA": "WIA recipient",
    "waitlist.situationCaregiver": "Caregiver / family member",
    "waitlist.situationOther": "Other",
    "waitlist.submit": "Join Waitlist",
    "waitlist.submitting": "Joining...",
    "waitlist.success.title": "You're on the list!",
    "waitlist.success.desc": "Thank you for your interest in FAB. We'll notify you as soon as early access is available.",
    "waitlist.success.close": "Close",
    "waitlist.success.alreadyTitle": "You're already on the list!",
    "waitlist.success.alreadyDesc": "This email is already registered. We'll notify you as soon as early access is available.",
    "waitlist.privacy": "We respect your privacy. No spam, ever.",

    // How It Works page
    "hiwPage.badge": "How FAB Works",
    "hiwPage.title1": "Your Journey from",
    "hiwPage.titleHighlight": "Chaos to Clarity",
    "hiwPage.desc": "A detailed walkthrough of how FAB turns supported source evidence into reviewable bookkeeping and governed provider work.",
    "hiwPage.step": "Step",
    "hiwPage.stepOne": "Step One",
    "hiwPage.step1.title": "Connect Supported Sources",
    "hiwPage.step1.desc": "You authorize each supported source separately. FAB reports whether it can read, prepare, submit, or only provide a supervised handoff, and never treats missing capability as a successful integration.",
    "hiwPage.step1.gmail": "Invoices, receipts, and financial confirmations from your inbox.",
    "hiwPage.step1.whatsapp": "Receipt photos can be uploaded through supported intake paths; direct WhatsApp intake is roadmap work.",
    "hiwPage.step1.drive": "Scanned documents, spreadsheets, and financial records.",
    "hiwPage.step1.bank": "Supported statement imports feed local transaction reconciliation; direct PSD2 access is capability gated.",
    "hiwPage.step1.mgz": "FAB prepares a supervised master-ledger artifact; direct account mutation is not currently live.",
    "hiwPage.step1.wave": "FAB mirrors supported Wave entities and prepares approval-gated bookkeeping operations and receipt delivery work.",
    "hiwPage.step1.svb": "FAB can classify and report PGB evidence; it does not currently submit SVB declarations or payments.",
    "hiwPage.step1.cash": "Manual input or photo scanning of cash receipts via mobile.",
    "hiwPage.step1.secure": "Secure by Design",
    "hiwPage.step1.secureDesc": "Supported Google sources use owner OAuth consent, Wave uses a locally encrypted token, and readiness APIs expose state without returning secret values.",
    "hiwPage.stepTwo": "Step Two",
    "hiwPage.step2.title": "AI Extracts & Categorizes",
    "hiwPage.step2.desc": "For supported documents, FAB records OCR output, normalized fields, confidence, provenance, duplicate evidence, and category suggestions.",
    "hiwPage.step2.scan": "Scan",
    "hiwPage.step2.scanTitle": "Document Scanning",
    "hiwPage.step2.scanDesc": "OCR reads receipts, invoices, and statements — extracting amounts, dates, vendors, and descriptions.",
    "hiwPage.step2.classify": "Classify",
    "hiwPage.step2.classifyTitle": "AI Classification",
    "hiwPage.step2.classifyDesc": "Rules and an optional approved model propose categories; uncertain transactions remain in review.",
    "hiwPage.step2.map": "Map",
    "hiwPage.step2.mapTitle": "Source Mapping",
    "hiwPage.step2.mapDesc": "Each transaction is mapped to its income source or expenditure destination based on your defined rules.",
    "hiwPage.step2.score": "Score",
    "hiwPage.step2.scoreTitle": "Confidence Scoring",
    "hiwPage.step2.scoreDesc": "Each classification records confidence. Only eligible local steps proceed; uncertainty, compliance risk, and external changes remain gated.",
    "hiwPage.step2.extractTitle": "What the AI Extracts from Each Document",
    "hiwPage.step2.vendorName": "Vendor Name",
    "hiwPage.step2.vendorEx": "Albert Heijn, Apotheek, etc.",
    "hiwPage.step2.amount": "Amount",
    "hiwPage.step2.amountEx": "€47.50, €125.00, etc.",
    "hiwPage.step2.date": "Date",
    "hiwPage.step2.dateEx": "2026-03-01, etc.",
    "hiwPage.step2.category": "Category",
    "hiwPage.step2.categoryEx": "Healthcare, Household, etc.",
    "hiwPage.step2.invoice": "Invoice Number",
    "hiwPage.step2.invoiceEx": "INV-2026-0042",
    "hiwPage.step2.payment": "Payment Method",
    "hiwPage.step2.paymentEx": "iDEAL, Cash, Card",
    "hiwPage.step2.taxDeduct": "Tax Deductible",
    "hiwPage.step2.taxDeductEx": "Yes / No",
    "hiwPage.step2.earmarked": "Earmarked Fund",
    "hiwPage.step2.earmarkedEx": "PGB, WLZ, WMO",
    "hiwPage.stepThree": "Step Three",
    "hiwPage.step3.title": "Route, Approve & Verify",
    "hiwPage.step3.desc": "FAB applies reviewed routing rules, prepares external drafts, records approvals, and verifies downstream state where the connector supports readback.",
    "hiwPage.step3.routing": "Intelligent Routing",
    "hiwPage.step3.r1from": "Household expenses",
    "hiwPage.step3.r1to": "MijnGeldzaken supervised export",
    "hiwPage.step3.r2from": "Side-hustle income/expenses",
    "hiwPage.step3.r2to": "WaveApps (Business)",
    "hiwPage.step3.r3from": "Health-related costs",
    "hiwPage.step3.r3to": "WaveApps (Personal)",
    "hiwPage.step3.r4from": "PGB care worker payments",
    "hiwPage.step3.r4to": "SVB reporting only",
    "hiwPage.step3.routingNote": "The local master ledger records each handoff, its evidence, and its verification state to reduce duplicate or unsupported posting.",
    "hiwPage.step3.autoComplete": "Review-Gated Data Completion",
    "hiwPage.step3.ac1": "Gap Detection",
    "hiwPage.step3.ac1Desc": "FAB scans the books and identifies entries with missing vendor name, amount, date, or invoice number.",
    "hiwPage.step3.ac2": "Contact Identification",
    "hiwPage.step3.ac2Desc": "Using existing data clues, FAB determines which party to contact for the missing information.",
    "hiwPage.step3.ac3": "Email Drafting",
    "hiwPage.step3.ac3Desc": "A professional email is crafted using a standard template, requesting the specific missing details.",
    "hiwPage.step3.ac4": "User Approval",
    "hiwPage.step3.ac4Desc": "You review and approve the email before it's sent from your inbox. Full control, always.",
    "hiwPage.step3.ac5": "Response Processing",
    "hiwPage.step3.ac5Desc": "A vendor response is retained as evidence and proposed corrections remain reviewable before bookkeeping changes.",
    "hiwPage.step3.ac6": "Follow-Up",
    "hiwPage.step3.ac6Desc": "Follow-up drafts can be scheduled within configured limits; external sending remains separately authorized.",
    "hiwPage.step3.sync": "Scheduled Processing",
    "hiwPage.step3.syncDesc": "Configured workers run eligible local tasks and supported read-only syncs. Provider availability and rate limits remain visible.",
    "hiwPage.step3.syncPlatform": "Platform Sync",
    "hiwPage.step3.syncPlatformFreq": "Configured schedule",
    "hiwPage.step3.syncPlatformDesc": "Refresh only providers with a configured and supported read capability.",
    "hiwPage.step3.syncSource": "Source Scanning",
    "hiwPage.step3.syncSourceFreq": "Configured schedule",
    "hiwPage.step3.syncSourceDesc": "Check consented Gmail and Drive sources plus local intake for supported documents.",
    "hiwPage.step3.syncData": "Data Completion",
    "hiwPage.step3.syncDataFreq": "Configured schedule",
    "hiwPage.step3.syncDataDesc": "Refresh review queues and recovery candidates without silently changing external systems.",
    "hiwPage.step3.adjustable": "Adjustable via settings",
    "hiwPage.stepFour": "Step Four",
    "hiwPage.step4.title": "Review & Control",
    "hiwPage.step4.desc": "The queue groups uncertainty, duplicate evidence, mapping gaps, reconciliation discrepancies, and external drafts so no unresolved decision is hidden.",
    "hiwPage.step4.queue": "Your Review Queue",
    "hiwPage.step4.queueNote": "Counts and priorities come from the live local ledger; FAB does not display fabricated throughput examples.",
    "hiwPage.step4.unknownVendor": "Unknown Vendor",
    "hiwPage.step4.vendorName": "Vendor name",
    "hiwPage.step4.healthcare": "Healthcare?",
    "hiwPage.step4.categoryLabel": "Category",
    "hiwPage.step4.healthHousehold": "Healthcare / Household?",
    "hiwPage.step4.householdSide": "Household / Side-hustle?",
    "hiwPage.step4.summary": "This Week's Summary",
    "hiwPage.step4.autoProcessed": "transactions auto-processed",
    "hiwPage.step4.needReview": "items need your review",
    "hiwPage.step4.totalProcessed": "total processed this week",
    "hiwPage.step4.healthCosts": "healthcare costs identified",
    "hiwPage.step4.timeSaved": "Time Saved",
    "hiwPage.step4.hoursWeek": "hours this week",
    "hiwPage.step4.compared": "Compared to manual bookkeeping",
    "hiwPage.flow.label": "The Complete Picture",
    "hiwPage.flow.title": "End-to-End Data Flow",
    "hiwPage.flow.desc": "From scattered documents to structured clarity — here's the complete journey of your financial data through FAB.",
    "hiwPage.flow.sources": "Data Sources",
    "hiwPage.flow.engine": "FAB Processing Engine",
    "hiwPage.flow.endStations": "End-Station Platforms",
    "hiwPage.flow.household": "Household",
    "hiwPage.flow.sideHustle": "Side-Hustle",
    "hiwPage.flow.healthcareType": "Healthcare",
    "hiwPage.flow.pgbPayments": "PGB Payments",
    "hiwPage.flow.result": "Result",
    "hiwPage.flow.resultTitle": "Complete Financial Clarity",
    "hiwPage.flow.resultDesc": "Unified local view of supported sources, reviewed categories, and provider handoff state",
    "hiwPage.flow.ocrExtraction": "OCR Extraction",
    "hiwPage.flow.aiClassification": "AI Classification",
    "hiwPage.flow.sourceMapping": "Source Mapping",
    "hiwPage.flow.confidenceScoring": "Confidence Scoring",
    "hiwPage.flow.gapDetection": "Gap Detection",
    "hiwPage.flow.autoEmail": "Auto-Email",

    // Footer legal items
    "footer.legal.privacypolicy": "Privacy Policy",
    "footer.legal.termsofservice": "Terms of Service",
    "footer.legal.gdpr": "GDPR",
    "footer.legal.cookiepolicy": "Cookie Policy",

    // Payment pages
    "payment.verifying": "Verifying your payment...",
    "payment.success.title": "Usage billing ready",
    "payment.success.desc": "Your payment method is ready for verified usage invoices. FAB charges resource cost x 2.5 and has no fixed monthly fee.",
    "payment.success.emailNote": "Billing contact",
    "payment.success.cta": "Go to Dashboard",
    "payment.error.title": "Something Went Wrong",
    "payment.error.desc": "We couldn't verify your payment. If you believe this is an error, please contact our support team.",
    "payment.error.cta": "Contact Support",
    "payment.cancel.title": "Payment Cancelled",
    "payment.cancel.desc": "No worries — you can always come back and subscribe when you're ready. Your data is safe with us.",
    "payment.cancel.cta": "Back to Home",

    // Account page
    "account.title": "My Account",
    "account.welcome": "Welcome back",
    "account.user": "User",
    "account.subtitle": "Manage usage billing, invoices, and account settings.",
    "account.loginRequired": "Sign In Required",
    "account.loginRequiredDesc": "Please sign in to access your account settings and subscription details.",
    "account.profile": "Profile",
    "account.logout": "Sign Out",
    "account.name": "Name",
    "account.email": "Email",
    "account.memberSince": "Member Since",
    "account.plan": "Current Plan",
    "account.freePlan": "Free Plan",
    "account.subscription": "Usage billing",
    "account.statusActive": "Active",
    "account.statusTrialing": "Trial",
    "account.statusPastDue": "Past Due",
    "account.statusCanceled": "Canceled",
    "account.statusFree": "Free",
    "account.currentPeriodEnd": "Current Period Ends",
    "account.autoRenew": "Auto-Renewal",
    "account.cancelAtEnd": "Cancels at period end",
    "account.autoRenewYes": "Enabled",
    "account.manageBilling": "Manage Billing",
    "account.portalRedirect": "Opening billing portal...",
    "account.checkoutRedirect": "Redirecting to checkout...",
    "account.freePlanTitle": "You're on the Free Plan",
    "account.freePlanDesc": "Upgrade to Pay-As-You-Go for unlimited document processing, multi-bank connections, and priority support.",
    "account.upgradeCta": "Upgrade to Pay-As-You-Go",
    "account.invoices": "Invoice History",
    "account.noInvoices": "No invoices yet. Your invoices will appear here once you subscribe.",
    "account.invoiceDate": "Date",
    "account.invoiceAmount": "Amount",
    "account.invoiceStatus": "Status",
    "account.invoiceActions": "Actions",
    "account.viewInvoice": "View Invoice",
    "account.downloadPdf": "Download PDF",
    "nav.account": "Account",

    // Legal layout
    "legal.backHome": "Back to Home",
    "legal.lastUpdated": "Last updated",
  },

  nl: {
    // Navbar
    "nav.howItWorks": "Hoe Het Werkt",
    "nav.features": "Functies",
    "nav.security": "Beveiliging",
    "nav.pricing": "Prijzen",
    "nav.impact": "Impact",
    "nav.about": "Over Ons",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "nav.blog": "Blog",
    "nav.home": "Home",
    "nav.signIn": "Inloggen",
    "nav.getStarted": "Aan de Slag",

    // Hero
    "hero.badge": "Financiële Helderheid voor Iedereen",
    "hero.title1": "Breng Structuur &",
    "hero.titleHighlight": "Helderheid",
    "hero.title2": "in Je Financiën",
    "hero.desc": "FAB is een lokaal financieel operationeel platform voor documentinname, ondersteunde boekhouding, beoordeling, afstemming, rapportage en beheerste provider-overdrachten.",
    "hero.cta1": "Gratis Beginnen",
    "hero.cta2": "Bekijk Hoe Het Werkt",
    "hero.stat1": "<10 min/week",
    "hero.stat2": "E2E Versleuteld",
    "hero.stat3": "Desktop & Mobiel",

    // Problem
    "problem.label": "De Uitdaging",
    "problem.title": "Financiën Beheren Hoeft Geen Fulltime Baan Te Zijn",
    "problem.desc": "Voor mensen met een beperking of chronische ziekte is de financiële administratie verspreid over WhatsApp-berichten, e-mailinboxen, Google Drive-mappen en meerdere platforms. Deze chaos kost uren per week — tijd die beter besteed kan worden aan gezondheid en welzijn.",
    "problem.card1.title": "Verspreide Documenten",
    "problem.card1.desc": "Bonnetjes in WhatsApp, facturen in Gmail, afschriften in Drive. Geen enkele bron van waarheid voor je financiën.",
    "problem.card1.stat": "5+",
    "problem.card1.statLabel": "databronnen",
    "problem.card2.title": "Uren Handmatig Werk",
    "problem.card2.desc": "Handmatig transacties invoeren, leveranciers achterna zitten voor ontbrekende informatie, afstemmen tussen platforms.",
    "problem.card2.stat": "4-8",
    "problem.card2.statLabel": "uur per week",
    "problem.card3.title": "Verborgen Zorgkosten",
    "problem.card3.desc": "De werkelijke financiële impact van een beperking blijft onzichtbaar — verspreid over geoormerkte fondsen, verzekeringen en eigen bijdragen.",
    "problem.card3.stat": "€17K+",
    "problem.card3.statLabel": "extra jaarlijkse kosten",

    // How It Works
    "hiw.label": "Hoe Het Werkt",
    "hiw.title": "Van Chaos naar Helderheid in Vier Stappen",
    "hiw.desc": "FAB werkt stil op de achtergrond en transformeert verspreide financiële gegevens naar gestructureerde, bruikbare helderheid.",
    "hiw.step1.title": "Verbind & Beheer Je Platforms",
    "hiw.step1.desc": "Koppel alleen de bronnen die je kiest. Elke koppeling toont of deze live, begeleid of nog niet beschikbaar is.",
    "hiw.step2.title": "AI Extraheert & Categoriseert",
    "hiw.step2.desc": "FAB scant ondersteunde documenten, extraheert financiële gegevens met OCR en stelt categorieën voor met vertrouwen en herkomst.",
    "hiw.step3.title": "Auto-Routeren & Beheren",
    "hiw.step3.desc": "FAB bereidt beheerste routering en exports voor. Externe wijzigingen vereisen een ondersteunde koppeling, bewijs en de ingestelde goedkeuringspoort.",
    "hiw.step4.title": "Beoordelen & Beheersen",
    "hiw.step4.desc": "Beoordeel onzekerheid, duplicaten, mappings en externe concepten vanuit een wachtrij. FAB verbergt nooit werk waarvoor nog een beslissing nodig is.",

    // Features
    "features.orch.label": "Intelligente Orkestratie",
    "features.orch.title": "Eén Platform, Al Je Financiële Tools",
    "features.orch.desc": "FAB brengt lokale inname, beoordeling, routering, afstemming, rapportage en provider-overdrachten samen in een controleerbare workflow.",
    "features.orch.item1": "Expliciete status per koppeling",
    "features.orch.item2": "Geoormerkte fondsen mapping voor PGB",
    "features.orch.item3": "Configureerbare lokale verwerkingscycli",
    "features.orch.item4": "Conflictdetectie en beoordelingswachtrijen",
    "features.ai.label": "AI-Aangedreven Verwerking",
    "features.ai.title": "Bewijsbewuste Boekhoudassistentie",
    "features.ai.desc": "FAB extraheert en categoriseert documenten, bewaart vertrouwen en herkomst, en stuurt onzeker of onvolledig werk naar beoordeling.",
    "features.ai.item1": "OCR-scanning van bonnetjes en facturen",
    "features.ai.item2": "Goedkeuringsplichtige leveranciersconcepten",
    "features.ai.item3": "Op vertrouwen gebaseerd markeringssysteem",
    "features.ai.item4": "Continu leren van correcties",
    "features.dash.label": "Unified Dashboard",
    "features.dash.title": "Bekijk Je Volledige Financiële Beeld",
    "features.dash.desc": "Bekijk bronbewijs, boekingen, beoordelingen, afstemming, compliancebevindingen en providerlevering in een operationeel overzicht.",
    "features.dash.item1": "Actuele grootboek- en workflowstatus",
    "features.dash.item2": "Zorgkostenrapportages",
    "features.dash.item3": "Beoordeelbare belasting- en compliancesamenvattingen",
    "features.dash.item4": "Exporteren in universele formaten (CSV, PDF)",

    // Integrations
    "integrations.label": "Verbonden Platforms",
    "integrations.title": "Een Besturingslaag voor Bestaande Tools",
    "integrations.desc": "FAB is een lokale bron van waarheid die live API's, begeleide overdrachten, imports en roadmapfuncties zichtbaar van elkaar onderscheidt.",
    "integrations.mgz.title": "MijnGeldzaken.nl",
    "integrations.mgz.desc": "FAB bereidt een beoordeelbare master-ledgerexport voor begeleide verwerking in MijnGeldzaken voor. Directe accountwijzigingen worden niet als live gepresenteerd.",
    "integrations.mgz.tag": "Huishoudfinanciën",
    "integrations.wave.title": "Wave Apps",
    "integrations.wave.desc": "FAB spiegelt ondersteunde Wave-data en bereidt goedkeuringsplichtige bewerkingen voor. Bonlevering is pas voltooid na geverifieerde attachment-readback.",
    "integrations.wave.tag": "Boekhouding",
    "integrations.banks.title": "Nederlandse Banken",
    "integrations.banks.desc": "FAB importeert ondersteunde bankafschriftbestanden en stemt transacties lokaal af. Directe PSD2-feeds blijven geblokkeerd tot een provider is ingericht.",
    "integrations.banks.tag": "Bankieren",
    "integrations.svb.title": "SVB (Sociale Verzekeringsbank)",
    "integrations.svb.desc": "PGB- en SVB-gegevens kunnen lokaal worden gecategoriseerd en gerapporteerd. FAB voert momenteel geen directe declaraties of betaalverzoeken uit.",
    "integrations.svb.tag": "PGB-Beheer",
    "integrations.google.title": "Gmail & Google Drive",
    "integrations.google.desc": "Met toestemming van de eigenaar leest FAB ingestelde Gmail- en Drive-bronnen, dedupliceert bewijs en importeert ondersteunde documenten in de beoordeelbare lokale workflow.",
    "integrations.google.tag": "Documentbronnen",
    "integrations.more.title": "Meer Integraties Komen Eraan",
    "integrations.more.desc": "We breiden continu onze platformverbindingen uit. WhatsApp Business, Exact Online, Moneybird en meer staan op onze roadmap.",
    "integrations.more.tag": "Roadmap",
    "integrations.callout.title": "Mogelijkheden zijn expliciet",
    "integrations.callout.desc": "Elke koppeling toont gereedheid, ondersteunde acties, beoordelingsvereisten en bewijsstatus. Niet-ondersteunde externe wijzigingen blijven geblokkeerd.",
    "integrations.cta": "Bekijk Hoe Het Werkt",

    // Stats
    "stats.users": "Bron van Waarheid",
    "stats.usersSub": "Lokaal operationeel grootboek",
    "stats.budget": "Bewaarbeleid",
    "stats.budgetSub": "Configureerbare Nederlandse bewijshorizon",
    "stats.minutes": "Externe Wijzigingen",
    "stats.minutesSub": "Goedkeurings- en functiegated",
    "stats.saved": "Bewijsintegriteit",
    "stats.savedSub": "Checksums voor bron en bijlage",

    // Testimonials
    "testimonials.label": "Werkingsprincipes",
    "testimonials.title": "Automatisering Die Je Kunt Controleren",
    "testimonials.desc": "FAB werkt op basis van bewijs, expliciete bevoegdheid en herstelbare status, niet op basis van onbewezen resultaatclaims.",
    "testimonials.t1.quote": "Externe boekhoudwijzigingen vereisen een ondersteunde providerfunctie en de ingestelde goedkeuringsroute.",
    "testimonials.t1.name": "Goedkeuringspoort",
    "testimonials.t1.role": "Externe bewerkingen",
    "testimonials.t2.quote": "Elk geïmporteerd document behoudt bronherkomst en checksum voordat het door de boekhouding stroomt.",
    "testimonials.t2.name": "Bewijsketen",
    "testimonials.t2.role": "Documenten en bijlagen",
    "testimonials.t3.quote": "Lage OCR-zekerheid, onduidelijke categorieën, duplicaten en afwijkingen blijven zichtbaar voor beoordeling.",
    "testimonials.t3.name": "Menselijke Beoordeling",
    "testimonials.t3.role": "Onzekere beslissingen",
    "testimonials.t4.quote": "Een permanente noodstop blokkeert nieuwe autonome stappen en alleen een operator kan de verwerking hervatten.",
    "testimonials.t4.name": "Fail-Closed Besturing",
    "testimonials.t4.role": "Autonome workflows",
    "testimonials.trustBadge1": "Privacy Eerst",
    "testimonials.trustBadge2": "AVG-Conform",
    "testimonials.trustBadge3": "Nederlands Gebouwd",
    "testimonials.trustBadge4": "Open Source Kern",

    // Blog / Updates
    "blog.label": "Laatste Updates",
    "blog.title": "Nieuws & Inzichten",
    "blog.desc": "Blijf op de hoogte van FAB's ontwikkelingsreis, productmijlpalen en inzichten over financiële toegankelijkheid.",
    "blog.readMore": "Lees Meer",
    "blog.viewAll": "Bekijk Alle Updates",
    "blog.backToBlog": "Terug naar Blog",
    "blog.publishedOn": "Gepubliceerd op",
    "blog.minRead": "min lezen",
    "blog.noPosts": "Nog geen berichten. Kom snel terug!",
    "blog.pageTitle": "Blog & Updates",
    "blog.pageDesc": "Productmijlpalen, functievoorbeelden en inzichten over het toegankelijk maken van financieel beheer voor iedereen.",
    "blog.badge": "Blog & Updates",
    "blog.searchPlaceholder": "Zoek artikelen...",
    "blog.allPosts": "Alle Berichten",
    "blog.catUpdate": "Update",
    "blog.catMilestone": "Mijlpaal",
    "blog.catFeature": "Functie",
    "blog.catAnnouncement": "Aankondiging",
    "blog.catTechnology": "Technologie",
    "blog.catGuide": "Gids",
    "blog.noPostsDesc": "We werken aan nieuwe inhoud. Kom snel terug voor updates over de ontwikkeling van FAB.",
    "blog.readTime": "lezen",
    "blog.postNotFound": "Bericht Niet Gevonden",
    "blog.postNotFoundDesc": "Het blogbericht dat je zoekt bestaat niet of is verwijderd.",
    "blog.ctaTitle": "Vond je dit artikel leuk?",
    "blog.ctaDesc": "Ontdek meer updates en inzichten over de reis van FAB.",
    "blog.ctaButton": "Bekijk Alle Berichten",

    // Security
    "security.label": "Privacy & Beveiliging",
    "security.title": "Je Gegevens Blijven Van Jou",
    "security.desc": "FAB houdt het operationele grootboek standaard lokaal, beschermt opgeslagen koppelinggeheimen, gebruikt geauthenticeerd transport waar ingesteld en legt compliancebewijs vast voor beoordeling.",
    "security.e2e": "Beschermde Geheimen",
    "security.e2eDesc": "Koppelinggeheimen zijn lokaal versleuteld en worden nooit door gereedheids-API's teruggegeven",
    "security.gdpr": "Compliancebewijs",
    "security.gdprDesc": "Bewaar- en privacybevindingen blijven beoordeelbaar en zijn niet zelf-gecertificeerd",
    "security.bio": "Toegangsbeheer",
    "security.bioDesc": "Loopbackbeveiliging, lokale authenticatie en begrensde operatorbevoegdheid",
    "security.export": "Gegevensexport",
    "security.exportDesc": "Exporteer of verwijder al je gegevens op elk moment",
    "security.local": "Lokaal grootboek met expliciete provider-overdrachten",
    "security.2fa": "Provider-MFA blijft onder beheer van de provider",
    "security.emailApproval": "Goedkeuring voor externe communicatie",
    "security.offline": "Lokale kernbeoordeling werkt zonder providertoegang",
    "security.gdprExport": "Controleerbare bewaar- en exportfuncties",
    "security.trusted": "Alleen operators kunnen goedkeuren en de noodstop hervatten",

    // Pricing
    "pricing.label": "Prijzen",
    "pricing.title": "Betaal Alleen Wat Je Gebruikt",
    "pricing.desc": "FAB gebruikt een transparant, op gebruik gebaseerd prijsmodel. Je betaalt alleen voor de resources die je verbruikt — geen verborgen kosten, geen verrassingen.",
    "pricing.free.label": "Gratis",
    "pricing.free.price": "€0",
    "pricing.free.period": "/altijd",
    "pricing.free.desc": "Begin en ervaar de kernwaarde van FAB.",
    "pricing.free.item1": "3 transacties per week",
    "pricing.free.item2": "Alle platformintegraties",
    "pricing.free.item3": "AI-categorisatie",
    "pricing.free.item4": "Basisrapportages",
    "pricing.free.item5": "Desktop & mobiel toegang",
    "pricing.free.cta": "Gratis Starten",
    "pricing.payg.label": "Betaal Per Gebruik",
    "pricing.payg.formula": "Gebruik × 2,5",
    "pricing.payg.desc": "Eerlijke, transparante prijzen op basis van daadwerkelijk gebruik.",
    "pricing.payg.item1": "Onbeperkte transacties",
    "pricing.payg.item2": "Autonome gegevensaanvulling",
    "pricing.payg.item3": "Volledige e-mailautomatisering",
    "pricing.payg.item4": "Geavanceerde rapportages & belastingoverzichten",
    "pricing.payg.item5": "Real-time kostendashboard",
    "pricing.payg.item6": "Instelbare bestedingslimiet",
    "pricing.payg.item7": "Prioriteitsondersteuning",
    "pricing.payg.cta": "Aan de Slag",

    // Impact
    "impact.label": "Maatschappelijke Impact",
    "impact.title": "De Werkelijke Kosten van een Beperking Meten",
    "impact.desc": "FAB is meer dan een financiële tool. Door geanonimiseerde gegevens te aggregeren, kunnen we unieke rapporten publiceren over de werkelijke financiële last van leven met een beperking — bewijs voor beter beleid en ondersteuning.",
    "impact.card1.title": "Financiële Empowerment",
    "impact.card1.desc": "Geef tijd en energie terug aan mensen die het het meest nodig hebben.",
    "impact.card2.title": "Kostentransparantie",
    "impact.card2.desc": "Kwantificeer de werkelijke 'beperkingskostenpremie' op bevolkingsschaal.",
    "impact.card3.title": "Beleidsbewijs",
    "impact.card3.desc": "Geanonimiseerde gegevens voor beter beperkingsbeleid en ondersteuning.",
    "impact.card4.title": "Gemeenschapskracht",
    "impact.card4.desc": "Bouw een netwerk van empowered individuen die hun financiële realiteit begrijpen.",

    // CTA
    "cta.title": "Klaar om Helderheid in Je Financiën te Brengen?",
    "cta.desc": "Sluit je aan bij de beweging naar financiële empowerment. Begin met 3 gratis transacties per week en ervaar het verschil.",
    "cta.primary": "Gratis Beginnen",
    "cta.secondary": "Neem Contact Op",

    // Footer
    "footer.desc": "Financiële Structuur & Helderheid voor mensen die complexe gezondheidsgerelateerde financiën beheren in Nederland.",
    "footer.product": "Product",
    "footer.company": "Bedrijf",
    "footer.legal": "Juridisch",
    "footer.rights": "Alle rechten voorbehouden.",
    "footer.madeWith": "Gemaakt met",
    "footer.inNL": "in Nederland",

    // Contact page
    "contact.badge": "Neem Contact Op",
    "contact.title1": "Laten We een",
    "contact.titleHighlight": "Gesprek",
    "contact.desc": "Heb je vragen over FAB? Wil je weten hoe we helderheid in je financiën kunnen brengen? We horen graag van je.",
    "contact.form.firstName": "Voornaam",
    "contact.form.lastName": "Achternaam",
    "contact.form.email": "E-mailadres",
    "contact.form.topic": "Onderwerp",
    "contact.form.topicPlaceholder": "Selecteer een onderwerp",
    "contact.form.message": "Bericht",
    "contact.form.messagePlaceholder": "Vertel ons hoe we je kunnen helpen...",
    "contact.form.send": "Bericht Versturen",
    "contact.form.sending": "Versturen...",
    "contact.success.title": "Bericht Verzonden!",
    "contact.success.desc": "Bedankt voor je bericht. We nemen binnen 24 uur contact met je op.",
    "contact.success.another": "Nog een Bericht Sturen",
    "contact.success.backHome": "Terug naar Home",
    "contact.success.toast": "Bericht succesvol verzonden!",
    "contact.info.email": "E-mail Ons",
    "contact.info.response": "Reactietijd",
    "contact.info.responseVal": "Binnen 24 uur",
    "contact.info.location": "Locatie",
    "contact.info.locationVal": "Nederland",
    "contact.info.phone": "Telefoon",
    "contact.info.phoneVal": "Plan een gesprek",
    "contact.info.faq": "Bekijk onze FAQ",
    "contact.info.faqDesc": "Bekijk onze veelgestelde vragen voor directe antwoorden op veelvoorkomende vragen over FAB's functies, prijzen en beveiliging.",
    "contact.info.faqLink": "Bezoek FAQ",
    "contact.topic.select": "Selecteer een onderwerp...",
    "contact.topic.general": "Algemene Vraag",
    "contact.topic.demo": "Demo Aanvragen",
    "contact.topic.pricing": "Prijzen & Pakketten",
    "contact.topic.partnership": "Samenwerkingsmogelijkheden",
    "contact.topic.support": "Technische Ondersteuning",
    "contact.topic.accessibility": "Toegankelijkheidsvraag",
    "contact.topic.media": "Media & Pers",
    "contact.error.firstName": "Voornaam is verplicht",
    "contact.error.lastName": "Achternaam is verplicht",
    "contact.error.email": "E-mail is verplicht",
    "contact.error.emailInvalid": "Voer een geldig e-mailadres in",
    "contact.error.subject": "Selecteer een onderwerp",
    "contact.error.message": "Bericht is verplicht",
    "contact.error.messageLength": "Bericht moet minimaal 10 tekens bevatten",
    "contact.form.firstNamePlaceholder": "Je voornaam",
    "contact.form.lastNamePlaceholder": "Je achternaam",
    "contact.form.emailPlaceholder": "jij@voorbeeld.nl",
    "contact.form.messagePlaceholderLong": "Vertel ons hoe we je kunnen helpen...",

    // FAQbout page
    "about.badge": "Ons Verhaal",
    "about.title1": "Geboren uit",
    "about.titleHighlight": "Geleefde Ervaring",
    "about.title2": "Gebouwd voor Echte Mensen",
    "about.mission.label": "Onze Missie",
    "about.mission.title": "Financiële Helderheid in Minder Dan 10 Minuten Per Week",
    "about.different.label": "Wat Ons Anders Maakt",
    "about.values.label": "Onze Waarden",
    "about.impact.label": "Onze Impactvisie",
    "about.cta.title": "Doe Mee aan het Bouwen van Financiële Helderheid",
    "about.cta.desc": "Of je nu een PGB-houder bent, een Wajong-ontvanger, of financiën beheert met een chronische aandoening — FAB is voor jou gebouwd.",
    "about.cta.primary": "Gratis Beginnen",
    "about.cta.secondary": "Neem Contact Op",
    "about.hero.desc": "FAB is niet bedacht in een bestuurskamer. Het is geboren uit de dagelijkse realiteit van het beheren van een huishouden terwijl je navigeert door de financiële complexiteit die komt met chronische ziekte en beperking. We begrijpen de strijd omdat we die zelf hebben meegemaakt.",
    "about.problem.title1": "Het Probleem",
    "about.problem.titleHighlight": "Dat We Leefden",
    "about.problem.p1": "Leven met een chronische ziekte of beperking in Nederland betekent navigeren door een doolhof van financiële verplichtingen. Je huishoudelijke uitgaven worden op één plek bijgehouden, je PGB-betalingen lopen via de SVB, je bijverdiensten staan in WaveApps, en belangrijke bonnetjes zijn verspreid over WhatsApp-berichten, Gmail-inboxen en Google Drive-mappen.",
    "about.problem.p2": "Het resultaat is financiële chaos. Uren per week besteed aan handmatig gegevens invoeren, ontbrekende bonnetjes achterna zitten en proberen accounts af te stemmen tussen platforms die nooit ontworpen zijn om met elkaar te communiceren. Uren die mensen met gezondheidsproblemen simpelweg niet hebben.",
    "about.problem.p3pre": "Erger nog, deze fragmentatie maakt het onmogelijk om een fundamentele vraag te beantwoorden:",
    "about.problem.p3quote": "Wat kost mijn ziekte of beperking mij werkelijk?",
    "about.problem.p3post": "Zonder dat antwoord is er geen helderheid, geen controle en geen pad naar financiële stabiliteit.",
    "about.mission.subtitle": "Financiële Structuur en Helderheid,",
    "about.mission.subtitleHighlight": "Zonder de Last",
    "about.mission.desc": "Onze missie is repetitieve administratie te verminderen terwijl financiële beslissingen, onzeker bewijs en externe wijzigingen zichtbaar blijven voor de verantwoordelijke persoon.",
    "about.mission.pillar1.title": "Automatiseer de Chaos",
    "about.mission.pillar1.desc": "FAB extraheert ondersteunde documenten uit ingestelde lokale, Gmail-, Drive- en fotobronnen, valideert ze en stuurt onzekere resultaten naar beoordeling.",
    "about.mission.pillar2.title": "Orkestreer Je Ecosysteem",
    "about.mission.pillar2.desc": "We vervangen bestaande tools niet. FAB legt vast wat elke koppeling kan lezen, voorbereiden, indienen en verifiëren, met een lokaal master ledger als controleerbaar centrum.",
    "about.mission.pillar3.title": "Onthul de Werkelijke Kosten",
    "about.mission.pillar3.desc": "Beoordeelde categorieën en rapporten helpen gezondheidskosten onderzoeken zonder voorlopige classificaties als vaststaand feit te presenteren.",
    "about.different.subtitle": "Niet Zomaar Weer Een",
    "about.different.subtitleHighlight": "Financiële App",
    "about.different.desc": "De meeste financiële tools vragen jou het werk te doen. FAB doet het werk voor je. Dit is wat ons onderscheidt.",
    "about.different.item1.title": "Zelfaanvullende Boeken",
    "about.different.item1.desc": "Wanneer FAB ontbrekende informatie vindt, legt het het hiaat vast en kan het een opvolgconcept voorbereiden. Verzending en toepassing van een antwoord blijven goedkeurings- en bewijsafhankelijk.",
    "about.different.item2.title": "Privacy als Ontwerp",
    "about.different.item2.desc": "FAB draait lokaal en maakt provider-overdrachten expliciet. Koppelinggeheimen zijn lokaal versleuteld, diagnostiek verwijdert gevoelige waarden en externe API-blootstelling is zonder authenticatie geblokkeerd.",
    "about.different.item3.title": "Gebouwd voor het Nederlandse Systeem",
    "about.different.item3.desc": "FAB ondersteunt Nederlandse boekhouding, btw, bewaarbeleid en classificatie van zorgkosten; wettelijke conclusies blijven voorlopig tot ze zijn beoordeeld.",
    "about.different.item4.title": "Ontworpen voor Echte Mensen",
    "about.different.item4.desc": "FAB prioriteert de beoordelingswachtrij, verklaart blokkades en automatiseert geschikt lokaal werk zodat de operator zich kan richten op beslissingen die echt oordeel vragen.",
    "about.values.subtitle": "Principes Die",
    "about.values.subtitleHighlight": "Alles Sturen",
    "about.values.subtitleEnd": "Wat We Bouwen",
    "about.values.v1.title": "Empathie Eerst",
    "about.values.v1.desc": "Elke functie die we bouwen begint met de vraag: vermindert dit de last voor iemand die al meer beheert dan de meesten?",
    "about.values.v2.title": "Radicale Transparantie",
    "about.values.v2.desc": "Je gegevens zijn van jou. We geloven in volledige transparantie over hoe je informatie wordt verwerkt, opgeslagen en beschermd.",
    "about.values.v3.title": "Automatisering met Vertrouwen",
    "about.values.v3.desc": "AI moet voor je werken, niet je oordeel vervangen. FAB automatiseert het saaie werk maar geeft jou altijd het laatste woord bij onzekere beslissingen.",
    "about.values.v4.title": "Helderheid Boven Complexiteit",
    "about.values.v4.desc": "We voegen geen functies toe omwille van functies. Elk element in FAB bestaat om je dichter bij het begrijpen van je werkelijke financiële beeld te brengen.",
    "about.impact.biggerPicture": "Het Grotere Plaatje",
    "about.impact.title1": "De",
    "about.impact.titleHighlight": "Werkelijke Kosten",
    "about.impact.titleEnd": "van een Beperking Onthullen",
    "about.impact.p1": "Naast het helpen van individuen heeft FAB een bredere maatschappelijke missie. Vandaag de dag zijn er geen uitgebreide gegevens over wat chronische ziekte en beperking werkelijk kosten vergeleken met gezonde leeftijdsgenoten. De verborgen kosten — gespecialiseerde apparatuur, woningaanpassingen, dieetbehoeften, extra vervoer, verloren verdiencapaciteit — blijven onzichtbaar in publieke beleidsdiscussies.",
    "about.impact.p2": "Met toestemming van onze gebruikers kan FAB geanonimiseerde financiële gegevens aggregeren om het eerste bewijs op bevolkingsschaal te produceren van de beperkingskostenpremie. Deze gegevens kunnen beleidsmakers, belangenorganisaties en zorginstellingen informeren over de werkelijke financiële last die mensen met een beperking elke dag dragen.",
    "about.impact.p3": "We leven in een tijd waarin zelfs mensen met aanzienlijke gezondheidsproblemen gedwongen worden bijverdiensten te onderhouden om onverhaalbare kosten te dekken. FAB helpt niet alleen die realiteit te beheren — het helpt het zichtbaar te maken zodat het op een dag kan veranderen.",
    "about.impact.stat1": "Nederlandse Uitkeringsontvangers",
    "about.impact.stat1Detail": "Meer dan een miljoen mensen in Nederland ontvangen PGB, Wajong of WIA — elk met complexe financiële ecosystemen.",
    "about.impact.stat2": "Jaarlijkse PGB-Uitgaven",
    "about.impact.stat2Detail": "Miljarden euro's stromen jaarlijks door het PGB-systeem, beheerd door mensen die vaak de tools missen om het goed bij te houden.",
    "about.impact.stat3": "Extra Leefkosten",
    "about.impact.stat3Detail": "Onderzoek toont aan dat mensen met een beperking 30% of meer aan extra leefkosten hebben vergeleken met hun niet-gehandicapte leeftijdsgenoten.",
    "about.vision.label": "Onze Visie",
    "about.vision.title1": "Een Wereld Waarin Gezondheidsproblemen",
    "about.vision.titleHighlight": "Niet Bepalen",
    "about.vision.titleEnd": "Financiële Uitkomsten",
    "about.vision.p1": "We stellen ons een toekomst voor waarin niemand hoeft te kiezen tussen het beheren van hun gezondheid en het beheren van hun financiën. Waarin de werkelijke kosten van een beperking zichtbaar, erkend en aangepakt worden. Waarin technologie dient als een brug naar financiële onafhankelijkheid, niet als nog een barrière om te overwinnen.",
    "about.vision.p2": "Beginnend in Nederland zal FAB uitbreiden om mensen met complexe gezondheidsgerelateerde financiën in heel Europa en daarbuiten te bedienen. Want de behoefte aan financiële helderheid is universeel, zelfs als de systemen die de complexiteit creëren lokaal zijn.",

    // FAQ page
    "faq.badge": "Veelgestelde Vragen",
    "faq.title1": "Alles Wat Je Moet",
    "faq.titleHighlight": "Weten",
    "faq.desc": "Vind antwoorden op veelgestelde vragen over FAB, van gegevensprivacy en PGB-integratie tot ons prijsmodel en autonome functies.",
    "faq.search": "Zoek een vraag...",
    "faq.results": "resultaten",
    "faq.noResults": "Geen resultaten gevonden",
    "faq.noResultsDesc": "Probeer andere zoekwoorden of blader door de categorieën hieronder.",
    "faq.clear": "Wissen",
    "faq.cta.title": "Nog Vragen?",
    "faq.cta.desc": "Ons team staat klaar om te helpen. Neem contact op en we reageren binnen 24 uur.",
    "faq.cta.primary": "Stel een Vraag",
    "faq.cta.secondary": "Hoe Het Werkt",
    "faq.categories": "Categorieën",
    "faq.questions": "vragen",
    "faq.result": "resultaat",
    "faq.askDirectly": "Stel Ons Direct een Vraag",
    "faq.sidebarDesc": "Ons team begrijpt de unieke uitdagingen van het beheren van financiën gerelateerd aan een beperking.",
    "faq.contactUs": "Neem Contact Op",
    "faq.cat.general": "Algemeen",
    "faq.cat.general.desc": "Leer de basis over FAB en wat het doet",
    "faq.cat.privacy": "Gegevensprivacy & Beveiliging",
    "faq.cat.privacy.desc": "Hoe we je gevoelige financiële gegevens beschermen",
    "faq.cat.pgb": "PGB-Integratie",
    "faq.cat.pgb.desc": "Hoe FAB werkt met het Nederlandse PGB-systeem",
    "faq.cat.pricing": "Prijzen & Facturering",
    "faq.cat.pricing.desc": "Ons eerlijke, op gebruik gebaseerde prijsmodel begrijpen",
    "faq.cat.autonomous": "Autonome Functies",
    "faq.cat.autonomous.desc": "Hoe FAB's AI namens jou werkt",
    "faq.cat.technical": "Technisch & Installatie",
    "faq.cat.technical.desc": "Aan de slag en technische details",

    // Waitlist
    "waitlist.badge": "Vroege Toegang",
    "waitlist.title": "Wees de Eerste die FAB Ervaart",
    "waitlist.desc": "Schrijf je in voor onze wachtlijst om vroege toegang te krijgen bij lancering. We houden je op de hoogte van onze voortgang.",
    "waitlist.email": "E-mailadres",
    "waitlist.emailPlaceholder": "jij@voorbeeld.nl",
    "waitlist.name": "Volledige naam",
    "waitlist.namePlaceholder": "Je naam",
    "waitlist.situation": "Je situatie",
    "waitlist.situationPlaceholder": "Selecteer je situatie",
    "waitlist.situationPGB": "PGB-houder",
    "waitlist.situationWajong": "Wajong-ontvanger",
    "waitlist.situationWIA": "WIA-ontvanger",
    "waitlist.situationCaregiver": "Mantelzorger / familielid",
    "waitlist.situationOther": "Anders",
    "waitlist.submit": "Inschrijven",
    "waitlist.submitting": "Bezig...",
    "waitlist.success.title": "Je staat op de lijst!",
    "waitlist.success.desc": "Bedankt voor je interesse in FAB. We laten je weten zodra vroege toegang beschikbaar is.",
    "waitlist.success.close": "Sluiten",
    "waitlist.success.alreadyTitle": "Je staat al op de lijst!",
    "waitlist.success.alreadyDesc": "Dit e-mailadres is al geregistreerd. We laten je weten zodra vroege toegang beschikbaar is.",
    "waitlist.privacy": "We respecteren je privacy. Geen spam, ooit.",

    // How It Works page
    "hiwPage.badge": "Hoe FAB Werkt",
    "hiwPage.title1": "Je Reis van",
    "hiwPage.titleHighlight": "Chaos naar Helderheid",
    "hiwPage.desc": "Een gedetailleerde uitleg van hoe FAB ondersteund bronbewijs omzet in beoordeelbare boekhouding en beheerste providerwerkzaamheden.",
    "hiwPage.step": "Stap",
    "hiwPage.stepOne": "Stap Eén",
    "hiwPage.step1.title": "Koppel Ondersteunde Bronnen",
    "hiwPage.step1.desc": "Je autoriseert elke ondersteunde bron afzonderlijk. FAB toont of het kan lezen, voorbereiden, indienen of alleen een begeleide overdracht biedt en behandelt ontbrekende mogelijkheden nooit als een geslaagde integratie.",
    "hiwPage.step1.gmail": "Facturen, bonnen en financiële bevestigingen uit je inbox.",
    "hiwPage.step1.whatsapp": "Bonfoto's kunnen via ondersteunde innamepaden worden geüpload; directe WhatsApp-inname staat op de roadmap.",
    "hiwPage.step1.drive": "Gescande documenten, spreadsheets en financiële administratie.",
    "hiwPage.step1.bank": "Ondersteunde afschriftimports voeden lokale afstemming; directe PSD2-toegang blijft functiegated.",
    "hiwPage.step1.mgz": "FAB bereidt een begeleid master-ledgerbestand voor; directe accountwijzigingen zijn momenteel niet live.",
    "hiwPage.step1.wave": "FAB spiegelt ondersteunde Wave-entiteiten en bereidt goedkeuringsplichtige boekingen en bonlevering voor.",
    "hiwPage.step1.svb": "FAB kan PGB-bewijs classificeren en rapporteren; het dient momenteel geen SVB-declaraties of betalingen in.",
    "hiwPage.step1.cash": "Handmatige invoer of foto-scanning van contante bonnen via mobiel.",
    "hiwPage.step1.secure": "Veilig Ontworpen",
    "hiwPage.step1.secureDesc": "Ondersteunde Google-bronnen gebruiken OAuth-toestemming van de eigenaar, Wave gebruikt een lokaal versleuteld token en gereedheids-API's geven geen geheime waarden terug.",
    "hiwPage.stepTwo": "Stap Twee",
    "hiwPage.step2.title": "AI Extraheert & Categoriseert",
    "hiwPage.step2.desc": "Voor ondersteunde documenten legt FAB OCR-uitvoer, genormaliseerde velden, vertrouwen, herkomst, duplicaatbewijs en categoriesuggesties vast.",
    "hiwPage.step2.scan": "Scan",
    "hiwPage.step2.scanTitle": "Documentscannen",
    "hiwPage.step2.scanDesc": "OCR leest bonnen, facturen en afschriften — extraheert bedragen, datums, leveranciers en beschrijvingen.",
    "hiwPage.step2.classify": "Classificeer",
    "hiwPage.step2.classifyTitle": "AI-Classificatie",
    "hiwPage.step2.classifyDesc": "Regels en een optioneel goedgekeurd model stellen categorieën voor; onzekere transacties blijven ter beoordeling.",
    "hiwPage.step2.map": "Map",
    "hiwPage.step2.mapTitle": "Bronmapping",
    "hiwPage.step2.mapDesc": "Elke transactie wordt gekoppeld aan de inkomstenbron of uitgavenbestemming op basis van je gedefinieerde regels.",
    "hiwPage.step2.score": "Score",
    "hiwPage.step2.scoreTitle": "Vertrouwensscore",
    "hiwPage.step2.scoreDesc": "Elke classificatie krijgt een vertrouwensscore. Alleen geschikte lokale stappen gaan door; onzekerheid, compliancerisico en externe wijzigingen blijven gated.",
    "hiwPage.step2.extractTitle": "Wat de AI Extraheert uit Elk Document",
    "hiwPage.step2.vendorName": "Leveranciersnaam",
    "hiwPage.step2.vendorEx": "Albert Heijn, Apotheek, etc.",
    "hiwPage.step2.amount": "Bedrag",
    "hiwPage.step2.amountEx": "€47,50, €125,00, etc.",
    "hiwPage.step2.date": "Datum",
    "hiwPage.step2.dateEx": "01-03-2026, etc.",
    "hiwPage.step2.category": "Categorie",
    "hiwPage.step2.categoryEx": "Zorg, Huishoudelijk, etc.",
    "hiwPage.step2.invoice": "Factuurnummer",
    "hiwPage.step2.invoiceEx": "INV-2026-0042",
    "hiwPage.step2.payment": "Betaalmethode",
    "hiwPage.step2.paymentEx": "iDEAL, Contant, Pinpas",
    "hiwPage.step2.taxDeduct": "Fiscaal Aftrekbaar",
    "hiwPage.step2.taxDeductEx": "Ja / Nee",
    "hiwPage.step2.earmarked": "Geoormerkt Fonds",
    "hiwPage.step2.earmarkedEx": "PGB, WLZ, WMO",
    "hiwPage.stepThree": "Stap Drie",
    "hiwPage.step3.title": "Routeren, Goedkeuren & Verifiëren",
    "hiwPage.step3.desc": "FAB past beoordeelde routeringsregels toe, bereidt externe concepten voor, legt goedkeuringen vast en verifieert downstreamstatus waar de koppeling readback ondersteunt.",
    "hiwPage.step3.routing": "Intelligente Routering",
    "hiwPage.step3.r1from": "Huishoudelijke uitgaven",
    "hiwPage.step3.r1to": "Begeleide MijnGeldzaken-export",
    "hiwPage.step3.r2from": "Bijverdienste inkomsten/uitgaven",
    "hiwPage.step3.r2to": "WaveApps (Zakelijk)",
    "hiwPage.step3.r3from": "Zorggerelateerde kosten",
    "hiwPage.step3.r3to": "WaveApps (Persoonlijk)",
    "hiwPage.step3.r4from": "PGB-zorgverlenerbetalingen",
    "hiwPage.step3.r4to": "Alleen SVB-rapportage",
    "hiwPage.step3.routingNote": "Het lokale master ledger legt elke overdracht, het bewijs en de verificatiestatus vast om dubbele of niet-ondersteunde boekingen te beperken.",
    "hiwPage.step3.autoComplete": "Beoordelingsplichtige Gegevensaanvulling",
    "hiwPage.step3.ac1": "Gatendetectie",
    "hiwPage.step3.ac1Desc": "FAB scant de boeken en identificeert vermeldingen met ontbrekende leveranciersnaam, bedrag, datum of factuurnummer.",
    "hiwPage.step3.ac2": "Contactidentificatie",
    "hiwPage.step3.ac2Desc": "Met bestaande gegevensaanwijzingen bepaalt FAB welke partij te contacteren voor de ontbrekende informatie.",
    "hiwPage.step3.ac3": "E-mail Opstellen",
    "hiwPage.step3.ac3Desc": "Een professionele e-mail wordt opgesteld met een standaardsjabloon, waarin de specifieke ontbrekende details worden opgevraagd.",
    "hiwPage.step3.ac4": "Gebruikersgoedkeuring",
    "hiwPage.step3.ac4Desc": "Je beoordeelt en keurt de e-mail goed voordat deze vanuit je inbox wordt verzonden. Volledige controle, altijd.",
    "hiwPage.step3.ac5": "Antwoordverwerking",
    "hiwPage.step3.ac5Desc": "Een leveranciersantwoord wordt als bewijs bewaard en voorgestelde correcties blijven beoordeelbaar voor boekhoudwijzigingen.",
    "hiwPage.step3.ac6": "Opvolging",
    "hiwPage.step3.ac6Desc": "Opvolgconcepten kunnen binnen ingestelde limieten worden gepland; externe verzending blijft afzonderlijk geautoriseerd.",
    "hiwPage.step3.sync": "Geplande Verwerking",
    "hiwPage.step3.syncDesc": "Ingestelde workers voeren geschikte lokale taken en ondersteunde alleen-lezen synchronisaties uit. Providerbeschikbaarheid en ratelimieten blijven zichtbaar.",
    "hiwPage.step3.syncPlatform": "Platformsynchronisatie",
    "hiwPage.step3.syncPlatformFreq": "Ingesteld schema",
    "hiwPage.step3.syncPlatformDesc": "Vernieuw alleen providers met een ingestelde en ondersteunde leesfunctie.",
    "hiwPage.step3.syncSource": "Bronscannen",
    "hiwPage.step3.syncSourceFreq": "Ingesteld schema",
    "hiwPage.step3.syncSourceDesc": "Controleer toegestane Gmail- en Drive-bronnen plus lokale inname op ondersteunde documenten.",
    "hiwPage.step3.syncData": "Gegevensaanvulling",
    "hiwPage.step3.syncDataFreq": "Ingesteld schema",
    "hiwPage.step3.syncDataDesc": "Vernieuw beoordelingswachtrijen en herstelkandidaten zonder externe systemen stilzwijgend te wijzigen.",
    "hiwPage.step3.adjustable": "Aanpasbaar via instellingen",
    "hiwPage.stepFour": "Stap Vier",
    "hiwPage.step4.title": "Beoordelen & Beheersen",
    "hiwPage.step4.desc": "De wachtrij bundelt onzekerheid, duplicaatbewijs, mappinghiaten, afstemmingsverschillen en externe concepten zodat geen onopgeloste beslissing verborgen blijft.",
    "hiwPage.step4.queue": "Je Beoordelingswachtrij",
    "hiwPage.step4.queueNote": "Aantallen en prioriteiten komen uit het live lokale grootboek; FAB toont geen verzonnen doorvoervoorbeelden.",
    "hiwPage.step4.unknownVendor": "Onbekende Leverancier",
    "hiwPage.step4.vendorName": "Leveranciersnaam",
    "hiwPage.step4.healthcare": "Zorg?",
    "hiwPage.step4.categoryLabel": "Categorie",
    "hiwPage.step4.healthHousehold": "Zorg / Huishoudelijk?",
    "hiwPage.step4.householdSide": "Huishoudelijk / Bijverdienste?",
    "hiwPage.step4.summary": "Samenvatting Deze Week",
    "hiwPage.step4.autoProcessed": "transacties automatisch verwerkt",
    "hiwPage.step4.needReview": "items hebben je beoordeling nodig",
    "hiwPage.step4.totalProcessed": "totaal verwerkt deze week",
    "hiwPage.step4.healthCosts": "zorgkosten geïdentificeerd",
    "hiwPage.step4.timeSaved": "Tijd Bespaard",
    "hiwPage.step4.hoursWeek": "uur deze week",
    "hiwPage.step4.compared": "Vergeleken met handmatige boekhouding",
    "hiwPage.flow.label": "Het Complete Beeld",
    "hiwPage.flow.title": "End-to-End Gegevensstroom",
    "hiwPage.flow.desc": "Van verspreide documenten naar gestructureerde helderheid — hier is de complete reis van je financiële gegevens door FAB.",
    "hiwPage.flow.sources": "Gegevensbronnen",
    "hiwPage.flow.engine": "FAB Verwerkingsengine",
    "hiwPage.flow.endStations": "Eindstation-Platforms",
    "hiwPage.flow.household": "Huishoudelijk",
    "hiwPage.flow.sideHustle": "Bijverdienste",
    "hiwPage.flow.healthcareType": "Zorg",
    "hiwPage.flow.pgbPayments": "PGB-Betalingen",
    "hiwPage.flow.result": "Resultaat",
    "hiwPage.flow.resultTitle": "Volledige Financiële Helderheid",
    "hiwPage.flow.resultDesc": "Uniform lokaal overzicht van ondersteunde bronnen, beoordeelde categorieën en provider-overdrachten",
    "hiwPage.flow.ocrExtraction": "OCR-Extractie",
    "hiwPage.flow.aiClassification": "AI-Classificatie",
    "hiwPage.flow.sourceMapping": "Bronmapping",
    "hiwPage.flow.confidenceScoring": "Vertrouwensscore",
    "hiwPage.flow.gapDetection": "Gatendetectie",
    "hiwPage.flow.autoEmail": "Auto-E-mail",

    // Footer legal items
    "footer.legal.privacypolicy": "Privacybeleid",
    "footer.legal.termsofservice": "Algemene Voorwaarden",
    "footer.legal.gdpr": "AVG",
    "footer.legal.cookiepolicy": "Cookiebeleid",

    // Payment pages
    "payment.verifying": "Betaling verifiëren...",
    "payment.success.title": "Gebruiksfacturatie gereed",
    "payment.success.desc": "Je betaalmethode is gereed voor gecontroleerde gebruiksfacturen. FAB rekent resourcekosten x 2,5 en geen vast maandbedrag.",
    "payment.success.emailNote": "Factuurcontact",
    "payment.success.cta": "Ga naar Dashboard",
    "payment.error.title": "Er Ging Iets Mis",
    "payment.error.desc": "We konden je betaling niet verifiëren. Als je denkt dat dit een fout is, neem dan contact op met ons supportteam.",
    "payment.error.cta": "Contact Support",
    "payment.cancel.title": "Betaling Geannuleerd",
    "payment.cancel.desc": "Geen zorgen — je kunt altijd terugkomen en je abonneren wanneer je er klaar voor bent. Je gegevens zijn veilig bij ons.",
    "payment.cancel.cta": "Terug naar Home",

    // Account page
    "account.title": "Mijn Account",
    "account.welcome": "Welkom terug",
    "account.user": "Gebruiker",
    "account.subtitle": "Beheer je abonnement, facturering en accountinstellingen.",
    "account.loginRequired": "Inloggen Vereist",
    "account.loginRequiredDesc": "Log in om je accountinstellingen en abonnementsgegevens te bekijken.",
    "account.profile": "Profiel",
    "account.logout": "Uitloggen",
    "account.name": "Naam",
    "account.email": "E-mail",
    "account.memberSince": "Lid Sinds",
    "account.plan": "Huidig Abonnement",
    "account.freePlan": "Gratis Abonnement",
    "account.subscription": "Gebruiksfacturatie",
    "account.statusActive": "Actief",
    "account.statusTrialing": "Proefperiode",
    "account.statusPastDue": "Achterstallig",
    "account.statusCanceled": "Geannuleerd",
    "account.statusFree": "Gratis",
    "account.currentPeriodEnd": "Huidige Periode Eindigt",
    "account.autoRenew": "Automatische Verlenging",
    "account.cancelAtEnd": "Wordt geannuleerd aan het einde van de periode",
    "account.autoRenewYes": "Ingeschakeld",
    "account.manageBilling": "Facturering Beheren",
    "account.portalRedirect": "Factureringsportaal openen...",
    "account.checkoutRedirect": "Doorsturen naar afrekenen...",
    "account.freePlanTitle": "Je hebt het Gratis Abonnement",
    "account.freePlanDesc": "Upgrade naar Betaal per Gebruik voor onbeperkte documentverwerking, meerdere bankverbindingen en prioriteitsondersteuning.",
    "account.upgradeCta": "Upgrade naar Betaal per Gebruik",
    "account.invoices": "Factuurgeschiedenis",
    "account.noInvoices": "Nog geen facturen. Je facturen verschijnen hier zodra je een abonnement neemt.",
    "account.invoiceDate": "Datum",
    "account.invoiceAmount": "Bedrag",
    "account.invoiceStatus": "Status",
    "account.invoiceActions": "Acties",
    "account.viewInvoice": "Factuur Bekijken",
    "account.downloadPdf": "PDF Downloaden",
    "nav.account": "Account",

    // Legal layout
    "legal.backHome": "Terug naar Home",
    "legal.lastUpdated": "Laatst bijgewerkt",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("fab-lang");
      if (saved === "en" || saved === "nl") return saved;
    }
    return "en";
  });

  const setLang = useCallback((newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("fab-lang", newLang);
  }, []);

  const t = useCallback(
    (key: string) => translations[lang][key] || translations.en[key] || key,
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
